repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6

    hooks:
      # Run the Ruff formatter.
      - id: ruff-format
      # Run the Ruff linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.24.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
        language_version: python3.12

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.4.0
    hooks:
      - id: djade
        args: [ --target-version, "4.2" ]
        exclude: |
          (?x)^(
            charts/.*
            |.*\.py
          )$

  - repo: https://github.com/ambient-innovation/boa-restrictor
    rev: v1.5.1
    hooks:
      - id: boa-restrictor
        args: [ --config=pyproject.toml ]