repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the Ruff formatter.
      - id: ruff-format
      # Run the Ruff linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.22.2
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
        language_version: python3.12

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.3.2
    hooks:
      - id: djade
        args: [ --target-version, "4.2" ]
        exclude: |
          (?x)^(
            charts/.*
            |.*\.py
          )$
