# Generated by Django 5.1.7 on 2025-03-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("faction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100, verbose_name="Reason")),
                ("amount", models.IntegerField(verbose_name="Amount")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Month")),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faction.faction",
                        verbose_name="Faction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ("id",),
                "default_related_name": "transaction",
            },
        ),
    ]
