# Generated by Django 4.1.5 on 2023-01-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("faction", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(max_length=100, verbose_name="Reason")),
                ("amount", models.DecimalField(decimal_places=0, max_digits=8, verbose_name="Amount")),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faction.faction", verbose_name="Faction"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["id"],
                "default_related_name": "transaction",
            },
        ),
    ]
