# Generated by Django 5.1.6 on 2025-02-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="month",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Month"),
            preserve_default=False,
        ),
    ]
