# Generated by Django 4.2.5 on 2024-01-09 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "default_related_name": "transaction",
                "ordering": ("id",),
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
