# Generated by Django 4.2.5 on 2024-01-09 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0006_faction_fyrd_reserve"),
        ("finance", "0003_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
                verbose_name="Faction",
            ),
        ),
    ]
