# Generated by Django 4.1.5 on 2023-01-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("item", "0002_itemtype_alter_item_type"),
        ("skirmish", "0005_warrior_culture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("town_name", models.CharField(max_length=100, verbose_name="Town name")),
                ("available_items", models.ManyToManyField(to="item.item", verbose_name="Available items")),
                (
                    "available_mercenaries",
                    models.ManyToManyField(to="skirmish.warrior", verbose_name="Available mercenaries"),
                ),
            ],
            options={
                "verbose_name": "Marketplace",
                "verbose_name_plural": "Marketplaces",
                "default_related_name": "marketplaces",
            },
        ),
    ]
