# Generated by Django 5.1.6 on 2025-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "town_name",
                    models.CharField(max_length=100, verbose_name="Town name"),
                ),
                (
                    "available_items",
                    models.ManyToManyField(
                        blank=True, to="item.item", verbose_name="Available items"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketplace",
                "verbose_name_plural": "Marketplaces",
                "default_related_name": "marketplaces",
            },
        ),
    ]
