# Generated by Django 4.1.5 on 2023-01-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_alter_item_owner"),
        ("skirmish", "0006_alter_warrior_faction"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplace",
            name="available_items",
            field=models.ManyToManyField(blank=True, to="item.item", verbose_name="Available items"),
        ),
        migrations.AlterField(
            model_name="marketplace",
            name="available_mercenaries",
            field=models.ManyToManyField(blank=True, to="skirmish.warrior", verbose_name="Available mercenaries"),
        ),
    ]
