# Generated by Django 5.1.6 on 2025-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        ("quest", "0001_initial"),
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplace",
            name="available_mercenaries",
            field=models.ManyToManyField(
                blank=True, to="skirmish.warrior", verbose_name="Available mercenaries"
            ),
        ),
        migrations.AddField(
            model_name="marketplace",
            name="available_quests",
            field=models.ManyToManyField(
                blank=True, to="quest.quest", verbose_name="Available quests"
            ),
        ),
    ]
