# Generated by Django 5.1.6 on 2025-03-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_initial"),
        ("savegame", "0002_remove_savegame_marketplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplace",
            name="savegame",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace",
                to="savegame.savegame",
                verbose_name="Savegame",
            ),
            preserve_default=False,
        ),
    ]
