# Generated by Django 4.2.5 on 2024-01-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0001_initial"),
        ("marketplace", "0002_alter_marketplace_available_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplace",
            name="available_quests",
            field=models.ManyToManyField(blank=True, to="quest.quest", verbose_name="Available quests"),
        ),
    ]
