# Generated by Django 4.2.5 on 2024-01-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("skirmish", "0011_warrior_avatar_id"),
        ("faction", "0006_faction_fyrd_reserve"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(choices=[(1, "Easy"), (2, "Hard")], verbose_name="Difficulty"),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faction.faction", verbose_name="Faction"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest",
                "verbose_name_plural": "Quests",
                "default_related_name": "quests",
            },
        ),
        migrations.CreateModel(
            name="QuestContract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quest.quest", verbose_name="Quest"
                    ),
                ),
                ("warriors", models.ManyToManyField(to="skirmish.warrior", verbose_name="Warriors")),
            ],
            options={
                "verbose_name": "Quest contract",
                "verbose_name_plural": "Quest contracts",
                "default_related_name": "quest_contracts",
            },
        ),
    ]
