# Generated by Django 5.1.6 on 2025-02-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("faction", "0001_initial"),
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "loot",
                    models.PositiveSmallIntegerField(verbose_name="Loot (in silver)"),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Easy"), (2, "Hard")], verbose_name="Difficulty"
                    ),
                ),
                (
                    "target_faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faction.faction",
                        verbose_name="Target faction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest",
                "verbose_name_plural": "Quests",
                "default_related_name": "quests",
            },
        ),
        migrations.CreateModel(
            name="QuestContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepted_in_month",
                    models.PositiveSmallIntegerField(verbose_name="Accepted in month"),
                ),
                (
                    "assigned_warriors",
                    models.ManyToManyField(
                        to="skirmish.warrior", verbose_name="Assigned warriors"
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        help_text="Faction who signed up for the quest.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faction.faction",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quest.quest",
                        verbose_name="Quest",
                    ),
                ),
                (
                    "skirmish",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quest_contract",
                        to="skirmish.skirmish",
                        verbose_name="Related Skirmish",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest contract",
                "verbose_name_plural": "Quest contracts",
                "default_related_name": "quest_contracts",
            },
        ),
    ]
