# Generated by Django 4.2.17 on 2024-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0011_warrior_avatar_id"),
        ("quest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questcontract",
            name="warriors",
        ),
        migrations.AddField(
            model_name="questcontract",
            name="assigned_warriors",
            field=models.ManyToManyField(
                to="skirmish.warrior", verbose_name="Assigned warriors"
            ),
        ),
    ]
