# Generated by Django 4.2.17 on 2024-12-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0013_remove_skirmish_quest_contract"),
        ("faction", "0008_alter_faction_active_quest"),
        ("quest", "0002_remove_questcontract_warriors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questcontract",
            name="skirmish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="skirmish.skirmish",
                verbose_name="Related Skirmish",
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="faction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
                verbose_name="Target faction",
            ),
        ),
    ]
