# Generated by Django 6.1.1 on 2026-09-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_clear_rival_bulletin_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Quest name',
                'verbose_name_plural': 'Quest names',
                'default_related_name': 'quest_names',
            },
        ),
    ]
