# Generated by Django 4.2.17 on 2024-12-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0013_remove_skirmish_quest_contract"),
        ("quest", "0003_questcontract_skirmish_alter_quest_faction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questcontract",
            name="skirmish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="skirmish.skirmish",
                verbose_name="Related Skirmish",
            ),
        ),
    ]
