# Generated by Django 4.2.17 on 2024-12-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0009_alter_faction_active_quest"),
        ("quest", "0004_alter_questcontract_skirmish"),
    ]

    operations = [
        migrations.AddField(
            model_name="questcontract",
            name="faction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
            ),
            preserve_default=False,
        ),
    ]
