# Generated by Django 4.2.17 on 2024-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0005_questcontract_faction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quest",
            old_name="faction",
            new_name="target_faction",
        ),
        migrations.AddField(
            model_name="quest",
            name="loot",
            field=models.PositiveSmallIntegerField(
                default=50, verbose_name="Loot (in silver)"
            ),
            preserve_default=False,
        ),
    ]
