# Generated by Django 4.2.17 on 2024-12-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0009_alter_faction_active_quest"),
        ("quest", "0006_rename_faction_quest_target_faction_quest_loot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questcontract",
            name="faction",
            field=models.ForeignKey(
                help_text="Faction who signed up for the quest.",
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
            ),
        ),
    ]
