# Generated by Django 4.2.17 on 2024-12-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0013_remove_skirmish_quest_contract"),
        ("quest", "0007_alter_questcontract_faction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questcontract",
            name="skirmish",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quest_contract",
                to="skirmish.skirmish",
                verbose_name="Related Skirmish",
            ),
        ),
    ]
