# Generated by Django 5.1.4 on 2025-01-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0008_alter_questcontract_skirmish"),
    ]

    operations = [
        migrations.AddField(
            model_name="questcontract",
            name="accepted_in_week",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Accepted in week"
            ),
            preserve_default=False,
        ),
    ]
