"""
The Old Frisian name stock the provider draws from.

**These names are drafted, not collected.** Old English left an onomasticon and Old Irish left the
annals; Old Frisian left neither. Its corpus is legal prose from the thirteenth century onward, four
hundred years after the game stands, and what is known of a tenth-century Frisian's name has to be read
out of Latin charters and coin legends. A pool of the forty-odd names that survive that way would
collide on nearly every draw across twenty living warriors, so the pool below is composed instead: the
West Germanic elements Frisian shares with its neighbours, spelled by Old Frisian rules. That is the
same kind of name as the attested ones - "Folcbald" and "Aldgisl" are a prototheme and a deuterotheme
and nothing more - and the attested names stand in the list as themselves. What the composition supplies
is depth, not shape.

Orthography, applied to every entry below without exception:

- **No length marks.** Plain ASCII, no macron and no acute. The editions disagree about which vowels are
  long, and the mark carries nothing for anyone reading a war band roster.
- **"th" is written, and never "d".** "Thiadrik", not "Diedrik"; "Frith", not "Frid". The older Old
  Frisian texts write the dental fricative and the later ones have moved to a stop, and following the
  later ones would collapse the whole stock back into the modern Dutch this pool exists to replace.
  Thorn and eth themselves resolve to "th" - neither is on the player's keyboard.
- **Frisian vowels, not English ones.** This is what keeps the pool from reading as Old English, which
  it otherwise would, the two languages being as close as they are:
    - Germanic "au" gives "a" where Old English breaks it to "ea": "Adward", never "Eadweard".
    - There is no breaking before "r" plus a consonant: "Bern-", not "Beorn-"; "-hard", not "-heard";
      "Ald-", not "Eald-".
    - Old English "ae" gives "e": "Ethel-" would be the descendant, and the older "Athal-" is what the
      charters write, so "Athal-" is what stands here.
    - "-ulf", not "-wulf"; "Wolf-", not "Wulf-".
- **No Latinised endings.** The charters write "Ubbo" and "Poppo" because they are written in Latin; the
  man's name ends in the Old Frisian weak "-a". A "-o" on a roster is a scribe's ending, not a Frisian's.
- **One word per name.** No patronymic and no particle - both are later, and both would make a place
  name built on the name run to two words.

Place-name elements are the first half of a compound and generics the second, so an element is
capitalised and a generic is not: "Ald" + "werd" is "Aldwerd". Which may follow which is deliberately
unconstrained - every pairing reads as a plausible Frisian place name, and that is what makes a pool
this small go this far.
"""

# Male given names. Dithematic names dominate because the record's do: two elements from a small stock,
# recombined per family, which is why a war band reads as a war band rather than as a list of strangers.
# The short names at the end are the weak declension, whose nominative singular is "-a" - a masculine
# ending in Old Frisian, however it reads to a modern eye, and the one the provider's weak genitive is
# built for.
GIVEN_NAMES = (
    "Adbald",
    "Adbern",
    "Adbrand",
    "Adger",
    "Adgisl",
    "Adhard",
    "Adhelm",
    "Adlef",
    "Admer",
    "Admund",
    "Adred",
    "Adrik",
    "Adulf",
    "Adwald",
    "Adward",
    "Adwig",
    "Adwin",
    "Aldbern",
    "Aldbrand",
    "Aldfrith",
    "Aldger",
    "Aldgisl",
    "Aldhard",
    "Aldhelm",
    "Aldlef",
    "Aldmer",
    "Aldmund",
    "Aldred",
    "Aldrik",
    "Aldulf",
    "Aldward",
    "Aldwig",
    "Aldwin",
    "Alfbern",
    "Alfbod",
    "Alfger",
    "Alfhard",
    "Alfhelm",
    "Alflef",
    "Alfmer",
    "Alfmund",
    "Alfred",
    "Alfrik",
    "Alfwald",
    "Alfward",
    "Alfwig",
    "Alfwin",
    "Athalbald",
    "Athalbern",
    "Athalbrand",
    "Athalfrith",
    "Athalger",
    "Athalgisl",
    "Athalhard",
    "Athalhelm",
    "Athalmer",
    "Athalmund",
    "Athalred",
    "Athalrik",
    "Athalulf",
    "Athalwald",
    "Athalward",
    "Athalwig",
    "Athalwin",
    "Baldger",
    "Baldhard",
    "Baldhelm",
    "Baldmer",
    "Baldred",
    "Baldrik",
    "Baldulf",
    "Baldward",
    "Baldwig",
    "Baldwin",
    "Bernbald",
    "Bernfrith",
    "Bernhard",
    "Bernhelm",
    "Bernlef",
    "Bernmer",
    "Bernmund",
    "Bernred",
    "Bernrik",
    "Bernulf",
    "Bernwald",
    "Bernward",
    "Bernwig",
    "Bernwin",
    "Bodger",
    "Bodhard",
    "Bodmer",
    "Bodred",
    "Bodrik",
    "Bodwin",
    "Brunbald",
    "Brunger",
    "Brunhard",
    "Brunhelm",
    "Brunmer",
    "Brunmund",
    "Brunred",
    "Brunrik",
    "Brunulf",
    "Brunwald",
    "Brunward",
    "Brunwig",
    "Brunwin",
    "Everbald",
    "Everbern",
    "Everhard",
    "Everhelm",
    "Everlef",
    "Evermer",
    "Evermund",
    "Everulf",
    "Everwald",
    "Everward",
    "Everwig",
    "Everwin",
    "Folkbald",
    "Folkbern",
    "Folkbrand",
    "Folkger",
    "Folkgisl",
    "Folkhard",
    "Folkhelm",
    "Folklef",
    "Folkmer",
    "Folkmund",
    "Folkred",
    "Folkrik",
    "Folkulf",
    "Folkwald",
    "Folkward",
    "Folkwig",
    "Folkwin",
    "Frithbald",
    "Frithbern",
    "Frithger",
    "Frithgisl",
    "Frithlef",
    "Frithmer",
    "Frithmund",
    "Frithred",
    "Frithrik",
    "Frithulf",
    "Frithwald",
    "Frithward",
    "Frithwig",
    "Frithwin",
    "Gerbald",
    "Gerbern",
    "Gerbod",
    "Gerbrand",
    "Gerfrith",
    "Gerhard",
    "Gerhelm",
    "Gerlef",
    "Germund",
    "Gerulf",
    "Gerwald",
    "Gerward",
    "Gerwig",
    "Gerwin",
    "Godbald",
    "Godbern",
    "Godbrand",
    "Godfrith",
    "Godger",
    "Godgisl",
    "Godhard",
    "Godhelm",
    "Godlef",
    "Godmer",
    "Godmund",
    "Godred",
    "Godrik",
    "Godulf",
    "Godwald",
    "Godward",
    "Godwig",
    "Godwin",
    "Grimbald",
    "Grimbern",
    "Grimhard",
    "Grimhelm",
    "Grimlef",
    "Grimred",
    "Grimrik",
    "Grimulf",
    "Grimwald",
    "Grimward",
    "Grimwig",
    "Grimwin",
    "Hildbald",
    "Hildbern",
    "Hildbrand",
    "Hildger",
    "Hildgisl",
    "Hildmer",
    "Hildmund",
    "Hildred",
    "Hildrik",
    "Hildulf",
    "Hildwald",
    "Hildward",
    "Hildwig",
    "Hildwin",
    "Liafger",
    "Liafhard",
    "Liafhelm",
    "Liafmer",
    "Liafmund",
    "Liafred",
    "Liafrik",
    "Liafulf",
    "Liafwald",
    "Liafward",
    "Liafwig",
    "Liafwin",
    "Liudbald",
    "Liudbern",
    "Liudbrand",
    "Liudfrith",
    "Liudger",
    "Liudgisl",
    "Liudhard",
    "Liudhelm",
    "Liudlef",
    "Liudmer",
    "Liudmund",
    "Liudred",
    "Liudrik",
    "Liudulf",
    "Liudwald",
    "Liudward",
    "Liudwig",
    "Liudwin",
    "Meinbald",
    "Meinbern",
    "Meinbrand",
    "Meinfrith",
    "Meinhard",
    "Meinhelm",
    "Meinlef",
    "Meinred",
    "Meinrik",
    "Meinulf",
    "Meinwald",
    "Meinward",
    "Meinwig",
    "Meinwin",
    "Redbad",
    "Redbern",
    "Redbrand",
    "Redger",
    "Redgisl",
    "Redhard",
    "Redhelm",
    "Redlef",
    "Redmer",
    "Redmund",
    "Redrik",
    "Redulf",
    "Redwald",
    "Redward",
    "Redwig",
    "Redwin",
    "Reinbald",
    "Reinbern",
    "Reinbod",
    "Reinbrand",
    "Reinfrith",
    "Reinhard",
    "Reinhelm",
    "Reinlef",
    "Reinmer",
    "Reinmund",
    "Reinulf",
    "Reinwald",
    "Reinward",
    "Reinwig",
    "Reinwin",
    "Rikbald",
    "Rikbern",
    "Rikbrand",
    "Rikfrith",
    "Rikhard",
    "Rikhelm",
    "Riklef",
    "Rikmer",
    "Rikmund",
    "Rikred",
    "Rikulf",
    "Rikwald",
    "Rikward",
    "Rikwig",
    "Rikwin",
    "Sibald",
    "Sibhard",
    "Sibmer",
    "Sibrand",
    "Sibred",
    "Sibrik",
    "Sibulf",
    "Sibward",
    "Sibwin",
    "Sigbald",
    "Sigbern",
    "Sigbod",
    "Sigbrand",
    "Sigfrith",
    "Sighard",
    "Sighelm",
    "Siglef",
    "Sigmer",
    "Sigmund",
    "Sigred",
    "Sigrik",
    "Sigulf",
    "Sigwald",
    "Sigward",
    "Sigwig",
    "Sigwin",
    "Thankmer",
    "Thankmund",
    "Thankred",
    "Thankrik",
    "Thankulf",
    "Thankward",
    "Thankwin",
    "Thiadbald",
    "Thiadbern",
    "Thiadbrand",
    "Thiadfrith",
    "Thiadger",
    "Thiadgisl",
    "Thiadhard",
    "Thiadhelm",
    "Thiadlef",
    "Thiadmer",
    "Thiadmund",
    "Thiadred",
    "Thiadrik",
    "Thiadulf",
    "Thiadwald",
    "Thiadward",
    "Thiadwig",
    "Thiadwin",
    "Walbald",
    "Walbern",
    "Walbrand",
    "Walfrith",
    "Walger",
    "Walgisl",
    "Walhard",
    "Walhelm",
    "Walmer",
    "Walmund",
    "Walred",
    "Walrik",
    "Walulf",
    "Walward",
    "Walwig",
    "Walwin",
    "Wigbald",
    "Wigbern",
    "Wigbod",
    "Wigbrand",
    "Wigfrith",
    "Wighard",
    "Wighelm",
    "Wiglef",
    "Wigmer",
    "Wigmund",
    "Wigred",
    "Wigrik",
    "Wigulf",
    "Wigwald",
    "Wigward",
    "Wigwin",
    "Wilbald",
    "Wilbern",
    "Wilbrand",
    "Wilfrith",
    "Wilger",
    "Wilgisl",
    "Wilhard",
    "Wilhelm",
    "Wilmer",
    "Wilmund",
    "Wilred",
    "Wilrik",
    "Wilulf",
    "Wilwald",
    "Wilward",
    "Wilwig",
    "Wilwin",
    "Wolfbern",
    "Wolfbrand",
    "Wolfger",
    "Wolfgisl",
    "Wolfhard",
    "Wolfhelm",
    "Wolflef",
    "Wolfmer",
    "Wolfmund",
    "Wolfred",
    "Wolfrik",
    "Wolfwald",
    "Wolfward",
    "Wolfwig",
    "Wolfwin",
    "Abba",
    "Alda",
    "Bofa",
    "Dodda",
    "Eppa",
    "Folka",
    "Haya",
    "Igga",
    "Menna",
    "Poppa",
    "Reda",
    "Ricka",
    "Sibba",
    "Sicka",
    "Thiada",
    "Ubba",
    "Watta",
    "Wibba",
    "Wicka",
)

# First elements: what the place is like, what grows there, what lives there, and where it lies. Frisian
# rather than Dutch throughout - "sten" and not "steen", "hach" and not "hoog" - because a modern spelling
# in the first half undoes the generic in the second.
PLACE_ELEMENTS = (
    "Ald",
    "Ast",
    "Bek",
    "Berk",
    "Bever",
    "Brad",
    "Bregge",
    "Brek",
    "Ek",
    "Elm",
    "Ern",
    "Esk",
    "Falk",
    "Feld",
    "Fisk",
    "Gos",
    "Grat",
    "Gren",
    "Hach",
    "Hasel",
    "Hei",
    "Hors",
    "Kamp",
    "Kerk",
    "Klai",
    "Kran",
    "Krei",
    "Krik",
    "Lang",
    "Lech",
    "Litik",
    "Middel",
    "Mor",
    "Nia",
    "North",
    "Otter",
    "Rad",
    "Riad",
    "Salt",
    "Sand",
    "Skep",
    "Slat",
    "Slik",
    "Sten",
    "Suth",
    "Swart",
    "Swin",
    "Wei",
    "West",
    "Weter",
    "Willig",
    "Wit",
    "Wolf",
)

# Second elements: what the place actually is. Every one of them habitative or topographic and none of
# them a first element, so a compound never reads as two settlements stuck together. "-werd" and "-ward"
# are the same word twice, a dwelling mound, and both spellings are on the map - Ferwerd against Aduard -
# so both are here rather than one being picked as the right one.
PLACE_GENERICS = (
    "buren",
    "burch",
    "dam",
    "fen",
    "ga",
    "hem",
    "holt",
    "hus",
    "lond",
    "mar",
    "rip",
    "sate",
    "sil",
    "terp",
    "tille",
    "um",
    "wald",
    "ward",
    "werd",
    "wier",
)

# Bynames for telling two men of the same name apart. Colour and provenance only - "Adward Swart",
# "Folkmer Dena" - so none of them makes a claim about the man's build, his speed, his health or his
# nerve, which is what his nickname is already for and could then contradict.
BYNAMES = (
    "Ald",
    "Blank",
    "Brun",
    "Dena",
    "Franka",
    "Gre",
    "Jung",
    "Nia",
    "Norther",
    "Ostera",
    "Rad",
    "Sassa",
    "Suther",
    "Swart",
    "Walha",
    "Wester",
    "Wit",
)
