# Generated by Django 4.1.7 on 2023-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Weapon mastery"), (2, "Swiftness"), (3, "Shield wall")],
                        unique=True,
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training",
                "verbose_name_plural": "Trainings",
                "default_related_name": "trainings",
            },
        ),
    ]
