# Generated by Django 5.1.4 on 2024-12-31 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0010_faction_savegame"),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="faction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
                verbose_name="Faction",
            ),
            preserve_default=False,
        ),
    ]
