# Generated by Django 4.1.4 on 2022-12-28 09:12

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("locale", models.CharField(max_length=10, verbose_name="Locale")),
            ],
            options={
                "verbose_name": "Faction",
                "verbose_name_plural": "Factions",
                "default_related_name": "factions",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Type Weapon"), (2, "Type Armor")],
                        verbose_name="Type",
                    ),
                ),
                ("price", models.PositiveSmallIntegerField(verbose_name="Price")),
                (
                    "value",
                    models.CharField(
                        max_length=10,
                        validators=[apps.core.validators.dice_notation],
                        verbose_name="Value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "default_related_name": "items",
            },
        ),
        migrations.CreateModel(
            name="Warrior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "current_health",
                    models.PositiveSmallIntegerField(verbose_name="Current health"),
                ),
                (
                    "max_health",
                    models.PositiveSmallIntegerField(verbose_name="Maximum health"),
                ),
                (
                    "dexterity",
                    models.PositiveSmallIntegerField(verbose_name="Dexterity"),
                ),
                (
                    "armor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warrior_armor",
                        to="skirmish.item",
                        verbose_name="Armor",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skirmish.faction",
                        verbose_name="Faction",
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warrior_weapons",
                        to="skirmish.item",
                        verbose_name="Weapon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warrior",
                "verbose_name_plural": "Warriors",
                "default_related_name": "warriors",
            },
        ),
    ]
