# Generated by Django 4.1.5 on 2023-01-20 20:34

import django.db.models.deletion
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FightAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Simple attack"), (2, "Risky attack")], unique=True, verbose_name="Type"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.PositiveSmallIntegerField(choices=[(1, "Weapon"), (2, "Armor")], verbose_name="Type")),
                ("price", models.PositiveSmallIntegerField(verbose_name="Price")),
                (
                    "value",
                    models.CharField(
                        max_length=10, validators=[apps.core.validators.dice_notation], verbose_name="Value"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faction.faction", verbose_name="Owning faction"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "default_related_name": "items",
            },
        ),
        migrations.CreateModel(
            name="Warrior",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("current_health", models.SmallIntegerField(verbose_name="Current health")),
                ("max_health", models.PositiveSmallIntegerField(verbose_name="Maximum health")),
                ("current_morale", models.SmallIntegerField(verbose_name="Current morale")),
                ("max_morale", models.PositiveSmallIntegerField(verbose_name="Maximum morale")),
                ("experience", models.PositiveIntegerField(default=0, verbose_name="Experience")),
                (
                    "condition",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Healthy"), (2, "Unconscious"), (3, "Fleeing"), (4, "Dead")],
                        default=1,
                        verbose_name="Condition",
                    ),
                ),
                ("dexterity", models.PositiveSmallIntegerField(verbose_name="Dexterity")),
                (
                    "armor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warrior_armor",
                        to="skirmish.item",
                        verbose_name="Armor",
                    ),
                ),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faction.faction", verbose_name="Faction"
                    ),
                ),
                (
                    "weapon",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warrior_weapons",
                        to="skirmish.item",
                        verbose_name="Weapon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warrior",
                "verbose_name_plural": "Warriors",
                "default_related_name": "warriors",
            },
        ),
        migrations.CreateModel(
            name="Skirmish",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("current_round", models.PositiveSmallIntegerField(default=1, verbose_name="Current round")),
                (
                    "non_player_faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_player_skirmishes",
                        to="faction.faction",
                        verbose_name="Non-player faction",
                    ),
                ),
                (
                    "non_player_warriors",
                    models.ManyToManyField(
                        related_name="non_player_skirmishes", to="skirmish.warrior", verbose_name="Non-player warriors"
                    ),
                ),
                (
                    "player_faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_skirmishes",
                        to="faction.faction",
                        verbose_name="Player faction",
                    ),
                ),
                (
                    "player_warriors",
                    models.ManyToManyField(
                        related_name="player_skirmishes", to="skirmish.warrior", verbose_name="Player warriors"
                    ),
                ),
                (
                    "victorious_faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="victorious_skirmishes",
                        to="faction.faction",
                        verbose_name="Victorious faction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skirmish",
                "verbose_name_plural": "Skirmishes",
                "default_related_name": "skirmishes",
            },
        ),
        migrations.CreateModel(
            name="BattleHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(verbose_name="Message")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "skirmish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skirmish.skirmish", verbose_name="Skirmish"
                    ),
                ),
            ],
            options={
                "verbose_name": "Battle log",
                "verbose_name_plural": "Battle logs",
                "default_related_name": "battle_logs",
            },
        ),
    ]
