# Generated by Django 4.1.5 on 2023-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="strength",
            field=models.PositiveSmallIntegerField(default=5, verbose_name="Strength"),
            preserve_default=False,
        ),
    ]
