# Generated by Django 4.1.4 on 2022-12-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="condition",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Healthy"), (2, "Unconscious"), (3, "dead")],
                default=1,
                verbose_name="Condition",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Weapon"), (2, "Armor")], verbose_name="Type"
            ),
        ),
    ]
