# Generated by Django 5.2 on 2025-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="last_skirmish_action",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Simple attack"),
                    (2, "Risky attack"),
                    (3, "Fast attack"),
                    (4, "Defensive stance"),
                ],
                null=True,
            ),
        ),
    ]
