# Generated by Django 4.1.5 on 2023-01-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skirmish",
            name="victorious_faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="victorious_skirmishes",
                to="skirmish.faction",
                verbose_name="Victorious faction",
            ),
        ),
        migrations.AlterField(
            model_name="fightaction",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Simple attack"), (2, "Risky attack")], unique=True, verbose_name="Type"
            ),
        ),
    ]
