# Generated by Django 4.1.4 on 2022-12-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0002_warrior_condition_alter_item_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Battle log",
                "verbose_name_plural": "Battle logs",
                "default_related_name": "battle_logs",
            },
        ),
    ]
