# Generated by Django 5.2 on 2025-04-18 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0002_warrior_last_skirmish_action"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warrior",
            old_name="last_skirmish_action",
            new_name="last_used_skirmish_action",
        ),
    ]
