# Generated by Django 4.1.5 on 2023-01-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0002_skirmish_victorious_faction_alter_fightaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrior",
            name="armor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warrior_armor",
                to="skirmish.item",
                verbose_name="Armor",
            ),
        ),
        migrations.AlterField(
            model_name="warrior",
            name="weapon",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warrior_weapons",
                to="skirmish.item",
                verbose_name="Weapon",
            ),
        ),
    ]
