# Generated by Django 4.1.5 on 2023-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0003_alter_warrior_armor_alter_warrior_weapon"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="spare_items",
            field=models.ManyToManyField(blank=True, to="skirmish.item", verbose_name="Spare items"),
        ),
    ]
