# Generated by Django 5.2.17 on 2026-08-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skirmish', '0003_rename_last_skirmish_action_warrior_last_used_skirmish_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='skirmish',
            name='month',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Month'),
        ),
    ]
