# Generated by Django 4.1.4 on 2022-12-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0003_battlelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrior",
            name="current_health",
            field=models.SmallIntegerField(verbose_name="Current health"),
        ),
    ]
