# Generated by Django 4.1.5 on 2023-01-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0005_alter_faction_culture"),
        ("skirmish", "0004_alter_warrior_armor_alter_warrior_weapon_delete_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="culture",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="faction.culture", verbose_name="Culture"
            ),
            preserve_default=False,
        ),
    ]
