# Generated by Django 4.1.4 on 2022-12-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0004_alter_warrior_current_health"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrior",
            name="armor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warrior_armor",
                to="skirmish.item",
                verbose_name="Armor",
            ),
        ),
        migrations.AlterField(
            model_name="warrior",
            name="weapon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warrior_weapons",
                to="skirmish.item",
                verbose_name="Weapon",
            ),
        ),
        migrations.CreateModel(
            name="Skirmish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "non_player_faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_player_skirmishes",
                        to="skirmish.faction",
                        verbose_name="Faction",
                    ),
                ),
                (
                    "player_faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_skirmishes",
                        to="skirmish.faction",
                        verbose_name="Faction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skirmish",
                "verbose_name_plural": "Skirmishes",
                "default_related_name": "skirmishes",
            },
        ),
    ]
