# Generated by Django 4.1.5 on 2023-01-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0004_faction_spare_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faction",
            name="spare_items",
        ),
        migrations.AddField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="skirmish.faction",
                verbose_name="Owing faction",
            ),
            preserve_default=False,
        ),
    ]
