# Generated by Django 4.1.5 on 2023-01-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0005_remove_faction_spare_items_item_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skirmish.faction", verbose_name="Owning faction"
            ),
        ),
    ]
