# Generated by Django 5.2.17 on 2026-08-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skirmish', '0005_rename_skirmish_sides_to_attacker_and_defender'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='unpaid_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Unpaid months'),
        ),
    ]
