# Generated by Django 4.1.4 on 2022-12-30 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0005_alter_warrior_armor_alter_warrior_weapon_skirmish"),
    ]

    operations = [
        migrations.AddField(
            model_name="battlelog",
            name="skirmish",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="skirmish.skirmish",
                verbose_name="Skirmish",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="skirmish",
            name="non_player_faction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_player_skirmishes",
                to="skirmish.faction",
                verbose_name="Non-player faction",
            ),
        ),
        migrations.AlterField(
            model_name="skirmish",
            name="player_faction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_skirmishes",
                to="skirmish.faction",
                verbose_name="Player faction",
            ),
        ),
    ]
