# Generated by Django 4.1.5 on 2023-01-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0006_alter_warrior_faction"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="recruitment_price",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Recruitment price"),
        ),
    ]
