# Generated by Django 4.1.5 on 2023-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0006_alter_item_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skirmish",
            name="non_player_warriors",
        ),
        migrations.RemoveField(
            model_name="skirmish",
            name="warrior_round_actions",
        ),
        migrations.AddField(
            model_name="skirmish",
            name="dropped_loot",
            field=models.ManyToManyField(blank=True, to="skirmish.item", verbose_name="Dropped loot"),
        ),
        migrations.DeleteModel(
            name="SkirmishWarriorRoundAction",
        ),
    ]
