# Generated by Django 4.1.4 on 2022-12-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "skirmish",
            "0006_battlelog_skirmish_alter_skirmish_non_player_faction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skirmish",
            name="non_player_warriors",
            field=models.ManyToManyField(
                related_name="non_player_skirmishes",
                to="skirmish.warrior",
                verbose_name="Non-player warriors",
            ),
        ),
        migrations.AddField(
            model_name="skirmish",
            name="player_warriors",
            field=models.ManyToManyField(
                related_name="player_skirmishes",
                to="skirmish.warrior",
                verbose_name="Player warriors",
            ),
        ),
    ]
