# Generated by Django 4.1.4 on 2022-12-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0007_skirmish_non_player_warriors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FightAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Simple attack")], unique=True, verbose_name="Type"
                    ),
                ),
            ],
        ),
    ]
