# Generated by Django 6.1.1 on 2026-09-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0003_faction_is_defeated'),
        ('item', '0001_initial'),
        ('skirmish', '0007_warrior_strength_baseline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlehistory',
            options={'default_related_name': 'battle_logs', 'ordering': ('id',), 'verbose_name': 'Battle log', 'verbose_name_plural': 'Battle logs'},
        ),
        migrations.CreateModel(
            name='SkirmishSpoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Item taken'), (2, 'Silver looted'), (3, 'Quest reward')], verbose_name='Kind')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.faction', verbose_name='Gaining faction')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item', verbose_name='Item')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skirmish.skirmish', verbose_name='Skirmish')),
                ('warrior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skirmish.warrior', verbose_name='Taken from')),
            ],
            options={
                'verbose_name': 'Skirmish spoil',
                'verbose_name_plural': 'Skirmish spoils',
                'ordering': ('id',),
                'default_related_name': 'skirmish_spoils',
            },
        ),
        migrations.CreateModel(
            name='SkirmishWarriorGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gained_experience', models.PositiveIntegerField(default=0, verbose_name='Gained experience')),
                ('reached_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reached level')),
                ('gained_strength', models.PositiveSmallIntegerField(default=0, verbose_name='Gained strength')),
                ('gained_dexterity', models.PositiveSmallIntegerField(default=0, verbose_name='Gained dexterity')),
                ('gained_max_health', models.PositiveSmallIntegerField(default=0, verbose_name='Gained maximum health')),
                ('gained_max_morale', models.PositiveSmallIntegerField(default=0, verbose_name='Gained maximum morale')),
                ('new_monthly_salary', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='New monthly salary')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faction.faction', verbose_name='Faction')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skirmish.skirmish', verbose_name='Skirmish')),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skirmish.warrior', verbose_name='Warrior')),
            ],
            options={
                'verbose_name': 'Skirmish warrior growth',
                'verbose_name_plural': 'Skirmish warrior growths',
                'ordering': ('id',),
                'default_related_name': 'skirmish_warrior_growths',
                'constraints': [models.UniqueConstraint(fields=('skirmish', 'warrior'), name='unique_growth_per_warrior_and_skirmish')],
            },
        ),
    ]
