# Generated by Django 4.1.5 on 2023-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0007_warrior_recruitment_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="weekly_salary",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Weekly salary"),
        ),
    ]
