# Generated by Django 4.1.7 on 2023-02-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0008_warrior_weekly_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="dexterity_process",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Dexterity progress"),
        ),
        migrations.AddField(
            model_name="warrior",
            name="health_process",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Health progress"),
        ),
        migrations.AddField(
            model_name="warrior",
            name="morale_process",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Morale progress"),
        ),
        migrations.AddField(
            model_name="warrior",
            name="strength_process",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Strength progress"),
        ),
    ]
