# Generated by Django 6.1.1 on 2026-09-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('skirmish', '0008_record_what_a_fight_yielded'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkirmishBlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(verbose_name='Round')),
                ('attacker_action', models.PositiveSmallIntegerField(choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance')], verbose_name='Attacker action')),
                ('defender_action', models.PositiveSmallIntegerField(choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance')], verbose_name='Defender action')),
                ('outcome', models.PositiveSmallIntegerField(choices=[(1, 'Hit'), (2, 'Absorbed'), (3, 'Missed'), (4, 'Not thrown')], verbose_name='Outcome')),
                ('attack_dice', models.CharField(blank=True, max_length=10, verbose_name='Attack dice')),
                ('attack_modifier', models.SmallIntegerField(blank=True, null=True, verbose_name='Attack modifier')),
                ('attack_roll', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Attack roll')),
                ('attack_value', models.PositiveSmallIntegerField(default=0, verbose_name='Attack value')),
                ('defense_dice', models.CharField(max_length=10, verbose_name='Defense dice')),
                ('defense_modifier', models.SmallIntegerField(verbose_name='Defense modifier')),
                ('defense_roll', models.PositiveSmallIntegerField(verbose_name='Defense roll')),
                ('defense_value', models.PositiveSmallIntegerField(default=0, verbose_name='Defense value')),
                ('damage', models.PositiveSmallIntegerField(default=0, verbose_name='Damage')),
                ('attack_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blows_struck', to='item.itemtype', verbose_name='Weapon type')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blows_dealt', to='skirmish.warrior', verbose_name='Attacker')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blows_taken', to='skirmish.warrior', verbose_name='Defender')),
                ('defense_item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blows_absorbed', to='item.itemtype', verbose_name='Armor type')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skirmish.skirmish', verbose_name='Skirmish')),
            ],
            options={
                'verbose_name': 'Skirmish blow',
                'verbose_name_plural': 'Skirmish blows',
                'ordering': ('id',),
                'default_related_name': 'skirmish_blows',
            },
        ),
    ]
