# Generated by Django 4.1.4 on 2022-12-31 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0008_fightaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkirmishWarriorRoundAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.PositiveSmallIntegerField(verbose_name="Round")),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skirmish.fightaction",
                        verbose_name="Fight action",
                    ),
                ),
                (
                    "skirmish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skirmish.skirmish",
                        verbose_name="Skirmish",
                    ),
                ),
                (
                    "warrior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skirmish.warrior",
                        verbose_name="Warrior",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skirmish warrior round action",
                "verbose_name_plural": "Skirmish warrior round actions",
                "default_related_name": "skirmish_warrior_round_actions",
            },
        ),
        migrations.AddField(
            model_name="skirmish",
            name="warrior_round_actions",
            field=models.ManyToManyField(
                related_name="warrior_round_action_skirmishes",
                through="skirmish.SkirmishWarriorRoundAction",
                to="skirmish.warrior",
                verbose_name="Warrior Round Actions",
            ),
        ),
    ]
