# Generated by Django 4.1.5 on 2023-01-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0008_remove_skirmish_dropped_loot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skirmish",
            name="dropped_loot",
            field=models.ManyToManyField(blank=True, to="skirmish.item", verbose_name="Dropped loot"),
        ),
    ]
