# Generated by Django 6.1.1 on 2026-09-08 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skirmish', '0009_record_every_blow_of_a_fight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkirmishCasualty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fate', models.PositiveSmallIntegerField(choices=[(1, 'Fled the field'), (2, 'Knocked unconscious'), (3, 'Killed'), (4, 'Taken prisoner')], verbose_name='Fate')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skirmish.skirmish', verbose_name='Skirmish')),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skirmish.warrior', verbose_name='Warrior')),
            ],
            options={
                'verbose_name': 'Skirmish casualty',
                'verbose_name_plural': 'Skirmish casualties',
                'ordering': ('id',),
                'default_related_name': 'skirmish_casualties',
                'constraints': [models.UniqueConstraint(fields=('skirmish', 'warrior'), name='unique_casualty_per_warrior_and_skirmish')],
            },
        ),
    ]
