# Generated by Django 4.1.7 on 2023-02-20 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0009_warrior_dexterity_process_warrior_health_process_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warrior",
            old_name="dexterity_process",
            new_name="dexterity_progress",
        ),
        migrations.RenameField(
            model_name="warrior",
            old_name="health_process",
            new_name="health_progress",
        ),
        migrations.RenameField(
            model_name="warrior",
            old_name="morale_process",
            new_name="morale_progress",
        ),
        migrations.RenameField(
            model_name="warrior",
            old_name="strength_process",
            new_name="strength_progress",
        ),
    ]
