# Generated by Django 4.1.4 on 2022-12-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0009_skirmishwarriorroundaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skirmish",
            name="current_round",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Current round"
            ),
        ),
    ]
