# Generated by Django 4.1.5 on 2023-01-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "__first__"),
        ("skirmish", "0010_remove_skirmish_dropped_loot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faction.faction", verbose_name="Owning faction"
            ),
        ),
        migrations.AlterField(
            model_name="skirmish",
            name="non_player_faction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_player_skirmishes",
                to="faction.faction",
                verbose_name="Non-player faction",
            ),
        ),
        migrations.AlterField(
            model_name="skirmish",
            name="player_faction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_skirmishes",
                to="faction.faction",
                verbose_name="Player faction",
            ),
        ),
        migrations.AlterField(
            model_name="skirmish",
            name="victorious_faction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="victorious_skirmishes",
                to="faction.faction",
                verbose_name="Victorious faction",
            ),
        ),
        migrations.AlterField(
            model_name="warrior",
            name="faction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faction.faction", verbose_name="Faction"
            ),
        ),
        migrations.DeleteModel(
            name="Faction",
        ),
    ]
