# Generated by Django 4.1.5 on 2023-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0011_alter_item_owner_alter_skirmish_non_player_faction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="current_morale",
            field=models.SmallIntegerField(default=10, verbose_name="Current morale"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warrior",
            name="max_morale",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="Maximum morale"),
            preserve_default=False,
        ),
    ]
