# Generated by Django 4.2.17 on 2024-12-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0002_remove_questcontract_warriors_and_more"),
        ("skirmish", "0011_warrior_avatar_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="skirmish",
            name="quest_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skirmishes",
                to="quest.questcontract",
                verbose_name="Quest contract",
            ),
        ),
    ]
