# Generated by Django 4.2.17 on 2024-12-25 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0012_skirmish_quest_contract"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skirmish",
            name="quest_contract",
        ),
    ]
