# Generated by Django 4.1.5 on 2023-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skirmish", "0012_warrior_current_morale_warrior_max_morale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warrior",
            name="condition",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Healthy"), (2, "Unconscious"), (3, "Fleeing"), (4, "Dead")],
                default=1,
                verbose_name="Condition",
            ),
        ),
    ]
