# Generated by Django 5.1.4 on 2025-01-03 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skirmish", "0013_remove_skirmish_quest_contract"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SkirmishAction",
        ),
    ]
