# Generated by Django 5.1.4 on 2025-01-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savegame", "0009_alter_savegame_current_week"),
        ("skirmish", "0014_delete_skirmishaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrior",
            name="savegame",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="savegame.savegame",
                verbose_name="Savegame",
            ),
            preserve_default=False,
        ),
    ]
