# Generated by Django 5.1.6 on 2025-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("locale", models.CharField(max_length=10, verbose_name="Locale")),
            ],
            options={
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
                "default_related_name": "cultures",
            },
        ),
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "fyrd_reserve",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of warriors draft-able from the fyrd",
                        verbose_name="Fyrd reserve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faction",
                "verbose_name_plural": "Factions",
                "default_related_name": "factions",
            },
        ),
    ]
