# Generated by Django 4.1.5 on 2023-01-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faction", "0001_initial"),
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="captured_warriors",
            field=models.ManyToManyField(blank=True, to="skirmish.warrior", verbose_name="Captured warriors"),
        ),
        migrations.AddField(
            model_name="faction",
            name="stored_items",
            field=models.ManyToManyField(blank=True, to="skirmish.item", verbose_name="Stored items"),
        ),
    ]
