# Generated by Django 5.1.6 on 2025-03-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0002_initial"),
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="leader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leading_factions",
                to="skirmish.warrior",
                verbose_name="Leader",
            ),
        ),
    ]
