# Generated by Django 5.2.17 on 2026-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='is_defeated',
            field=models.BooleanField(default=False, verbose_name='Is defeated'),
        ),
    ]
