# Generated by Django 4.1.5 on 2023-01-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "0003_remove_faction_stored_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("locale", models.CharField(max_length=10, verbose_name="Locale")),
            ],
            options={
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
                "default_related_name": "cultures",
            },
        ),
        migrations.RemoveField(
            model_name="faction",
            name="locale",
        ),
        migrations.AddField(
            model_name="faction",
            name="culture",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="faction.culture", verbose_name="Culture"
            ),
        ),
    ]
