# Generated by Django 5.1.7 on 2025-03-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0003_faction_leader"),
        ("item", "0002_initial"),
        ("quest", "0001_initial"),
        ("skirmish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="available_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="available_shop_items",
                to="item.item",
                verbose_name="Available items",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="available_mercenaries",
            field=models.ManyToManyField(
                blank=True,
                related_name="available_pub_mercenaries",
                to="skirmish.warrior",
                verbose_name="Available mercenaries",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="available_quests",
            field=models.ManyToManyField(
                blank=True,
                related_name="available_town_quests",
                to="quest.quest",
                verbose_name="Available quests",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="town_name",
            field=models.CharField(
                default="Towny", max_length=100, verbose_name="Town name"
            ),
            preserve_default=False,
        ),
    ]
