# Generated by Django 4.1.5 on 2023-01-21 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0004_culture_remove_faction_locale_faction_culture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="culture",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="faction.culture", verbose_name="Culture"
            ),
            preserve_default=False,
        ),
    ]
