# Generated by Django 4.1.5 on 2023-02-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0005_alter_faction_culture"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="fyrd_reserve",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of warriors draft-able from the fyrd", verbose_name="Fyrd reserve"
            ),
        ),
    ]
