# Generated by Django 4.2.17 on 2024-12-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quest", "0004_alter_questcontract_skirmish"),
        ("faction", "0008_alter_faction_active_quest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="active_quest",
            field=models.ForeignKey(
                blank=True,
                help_text="There can only be one active quest at a time.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quest.questcontract",
                verbose_name="Active Quest",
            ),
        ),
    ]
