# Generated by Django 4.2.17 on 2024-12-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("savegame", "0006_alter_savegame_marketplace_and_more"),
        ("faction", "0009_alter_faction_active_quest"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="savegame",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="savegame.savegame",
                verbose_name="Savegame",
            ),
            preserve_default=False,
        ),
    ]
