# Generated by Django 5.1.4 on 2025-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0010_faction_savegame"),
        ("quest", "0008_alter_questcontract_skirmish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faction",
            name="active_quest",
        ),
        migrations.AddField(
            model_name="faction",
            name="active_quests",
            field=models.ManyToManyField(
                blank=True,
                help_text="There can only be one active quest at a time.",
                null=True,
                to="quest.questcontract",
                verbose_name="Active Quest",
            ),
        ),
    ]
