# Generated by Django 5.1.4 on 2025-01-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0011_remove_faction_active_quest_faction_active_quests"),
        ("quest", "0008_alter_questcontract_skirmish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="active_quests",
            field=models.ManyToManyField(
                blank=True,
                help_text="There can only be one active quest at a time.",
                to="quest.questcontract",
                verbose_name="Active Quest",
            ),
        ),
    ]
