# Generated by Django 5.1.6 on 2025-02-09 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("faction", "0001_initial"),
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Savegame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75, verbose_name="Name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lastmodified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "current_month",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Month will be incremented after creation via Command",
                        verbose_name="Current month",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "marketplace",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="savegame",
                        to="marketplace.marketplace",
                        verbose_name="Marketplace",
                    ),
                ),
                (
                    "player_faction",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_savegame",
                        to="faction.faction",
                        verbose_name="Player Faction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Savegame",
                "verbose_name_plural": "Savegames",
                "default_related_name": "savegames",
            },
        ),
    ]
