# Generated by Django 5.2.17 on 2026-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savegame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegame',
            name='outcome',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Running'), (2, 'Won'), (3, 'Lost')], default=1, verbose_name='Outcome'),
        ),
    ]
