# Generated by Django 4.2.17 on 2024-12-27 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("savegame", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savegame",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savegame",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savegame",
            name="lastmodified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
