# Generated by Django 5.1.6 on 2025-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savegame", "0002_remove_savegame_marketplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savegame",
            name="current_month",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Month will be incremented after creation via Command",
                verbose_name="Current month",
            ),
        ),
    ]
