# Generated by Django 4.2.17 on 2024-12-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0009_alter_faction_active_quest"),
        ("savegame", "0002_savegame_created_at_savegame_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savegame",
            name="player_faction",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
                verbose_name="Player Faction",
            ),
            preserve_default=False,
        ),
    ]
