# Generated by Django 4.2.17 on 2024-12-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savegame", "0003_savegame_player_faction"),
    ]

    operations = [
        migrations.AddField(
            model_name="savegame",
            name="current_week",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Current week"
            ),
        ),
    ]
