# Generated by Django 4.2.17 on 2024-12-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_marketplace_available_quests"),
        ("faction", "0009_alter_faction_active_quest"),
        ("savegame", "0005_savegame_marketplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savegame",
            name="marketplace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.marketplace",
                verbose_name="Marketplace",
            ),
        ),
        migrations.AlterField(
            model_name="savegame",
            name="player_faction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
                verbose_name="Player Faction",
            ),
        ),
    ]
