# Generated by Django 5.1.4 on 2024-12-29 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0010_faction_savegame"),
        ("marketplace", "0003_marketplace_available_quests"),
        ("savegame", "0007_alter_savegame_marketplace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savegame",
            name="marketplace",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="savegame",
                to="marketplace.marketplace",
                verbose_name="Marketplace",
            ),
        ),
        migrations.AlterField(
            model_name="savegame",
            name="player_faction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_savegame",
                to="faction.faction",
                verbose_name="Player Faction",
            ),
        ),
    ]
