# Generated by Django 4.1.5 on 2023-01-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerWeekLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                ("week", models.PositiveSmallIntegerField(verbose_name="Week")),
            ],
            options={
                "verbose_name": "Player week log",
                "verbose_name_plural": "Player week logs",
                "default_related_name": "player_week_logs",
            },
        ),
    ]
