# Generated by Django 5.1.4 on 2024-12-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("savegame", "0007_alter_savegame_marketplace_and_more"),
        ("week", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerweeklog",
            name="savegame",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="savegame.savegame",
                verbose_name="Savegame",
            ),
            preserve_default=False,
        ),
    ]
