# Generated by Django 5.1.4 on 2024-12-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0010_faction_savegame"),
        ("week", "0002_playerweeklog_savegame"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerweeklog",
            name="savegame",
        ),
        migrations.AddField(
            model_name="playerweeklog",
            name="faction",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
                verbose_name="Faction",
            ),
            preserve_default=False,
        ),
    ]
