# Generated by Django 5.1.4 on 2025-01-08 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("week", "0003_remove_playerweeklog_savegame_playerweeklog_faction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerweeklog",
            name="message",
        ),
    ]
