# Generated by Django 6.1.1 on 2026-09-09 09:00

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('locale', models.CharField(max_length=10, verbose_name='Locale')),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'default_related_name': 'cultures',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('function', models.PositiveSmallIntegerField(choices=[(1, 'Weapon'), (2, 'Armor')], verbose_name='Function')),
                ('base_value', models.CharField(max_length=10, validators=[apps.common.validators.dice_notation], verbose_name='Value')),
                ('svg_image_name', models.CharField(max_length=50, verbose_name='SVG image name')),
                ('is_fallback', models.BooleanField(default=0, verbose_name='Is fallback')),
            ],
            options={
                'verbose_name': 'Item type',
                'verbose_name_plural': 'Item types',
                'default_related_name': 'item_types',
            },
        ),
        migrations.CreateModel(
            name='QuestName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Quest name',
                'verbose_name_plural': 'Quest names',
                'default_related_name': 'quest_names',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('fyrd_reserve', models.PositiveSmallIntegerField(default=0, help_text='Number of warriors draft-able from the fyrd', verbose_name='Fyrd reserve')),
                ('is_defeated', models.BooleanField(default=False, verbose_name='Is defeated')),
                ('town_name', models.CharField(max_length=100, verbose_name='Town name')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.culture', verbose_name='Culture')),
            ],
            options={
                'verbose_name': 'Faction',
                'verbose_name_plural': 'Factions',
                'default_related_name': 'factions',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'Rusty'), (2, 'Cheap'), (3, 'Traditional'), (4, 'Superior')], default=3, verbose_name='Condition')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('modifier', models.SmallIntegerField(default=0, help_text='2d4+7 - this is the "7"', verbose_name='Modifier')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Owning faction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.itemtype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'default_related_name': 'items',
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='available_items',
            field=models.ManyToManyField(blank=True, related_name='available_shop_items', to='warband.item', verbose_name='Available items'),
        ),
        migrations.CreateModel(
            name='PlayerMonthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(blank=True, default='', verbose_name='Body')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (9, 'Quests offered'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed')], verbose_name='Kind')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Demands attention'), (2, 'Consequence'), (3, 'Upkeep'), (4, 'Chronicle')], verbose_name='Category')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Faction')),
            ],
            options={
                'verbose_name': 'Player month log',
                'verbose_name_plural': 'Player month logs',
                'ordering': ('-month', 'id'),
                'default_related_name': 'player_month_logs',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('loot', models.PositiveSmallIntegerField(verbose_name='Loot (in silver)')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Hard')], verbose_name='Difficulty')),
                ('expected_opposition', models.PositiveSmallIntegerField(verbose_name='Expected opposition')),
                ('target_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Target faction')),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
                'default_related_name': 'quests',
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='available_quests',
            field=models.ManyToManyField(blank=True, related_name='available_town_quests', to='warband.quest', verbose_name='Available quests'),
        ),
        migrations.CreateModel(
            name='QuestContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_in_month', models.PositiveSmallIntegerField(verbose_name='Accepted in month')),
                ('faction', models.ForeignKey(help_text='Faction who signed up for the quest.', on_delete=django.db.models.deletion.CASCADE, to='warband.faction')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.quest', verbose_name='Quest')),
            ],
            options={
                'verbose_name': 'Quest contract',
                'verbose_name_plural': 'Quest contracts',
                'default_related_name': 'quest_contracts',
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='active_quests',
            field=models.ManyToManyField(blank=True, help_text='There can only be one active quest at a time.', to='warband.questcontract', verbose_name='Active Quest'),
        ),
        migrations.CreateModel(
            name='Savegame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastmodified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('current_month', models.PositiveSmallIntegerField(default=1, help_text='Month will be incremented after creation via Command', verbose_name='Current month')),
                ('outcome', models.PositiveSmallIntegerField(choices=[(1, 'Running'), (2, 'Won'), (3, 'Lost')], default=1, verbose_name='Outcome')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('player_faction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_savegame', to='warband.faction', verbose_name='Player Faction')),
            ],
            options={
                'verbose_name': 'Savegame',
                'verbose_name_plural': 'Savegames',
                'default_related_name': 'savegames',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='savegame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.savegame', verbose_name='Savegame'),
        ),
        migrations.AddField(
            model_name='faction',
            name='savegame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.savegame', verbose_name='Savegame'),
        ),
        migrations.CreateModel(
            name='Skirmish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('current_round', models.PositiveSmallIntegerField(default=1, verbose_name='Current round')),
                ('month', models.PositiveSmallIntegerField(default=1, verbose_name='Month')),
                ('attacking_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_skirmishes', to='warband.faction', verbose_name='Attacking faction')),
                ('defending_faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_skirmishes', to='warband.faction', verbose_name='Defending faction')),
                ('victorious_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='victorious_skirmishes', to='warband.faction', verbose_name='Victorious faction')),
            ],
            options={
                'verbose_name': 'Skirmish',
                'verbose_name_plural': 'Skirmishes',
                'default_related_name': 'skirmishes',
            },
        ),
        migrations.AddField(
            model_name='questcontract',
            name='skirmish',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_contract', to='warband.skirmish', verbose_name='Related Skirmish'),
        ),
        migrations.CreateModel(
            name='BattleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.skirmish', verbose_name='Skirmish')),
            ],
            options={
                'verbose_name': 'Battle log',
                'verbose_name_plural': 'Battle logs',
                'ordering': ('id',),
                'default_related_name': 'battle_logs',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.PositiveSmallIntegerField(choices=[(0, 'No hall'), (1, 'Mead Hall'), (2, 'Great Hall'), (3, 'High Hall')], default=0)),
                ('weaponsmith', models.PositiveSmallIntegerField(choices=[(0, 'No weaponsmith'), (1, 'Smithy'), (2, 'Forge Hall'), (3, 'Master Forge')], default=0)),
                ('marketplace', models.PositiveSmallIntegerField(choices=[(0, 'No marketplace'), (1, 'Marketplace'), (2, 'Trading Post'), (3, 'High Market')], default=0)),
                ('sanctuary', models.PositiveSmallIntegerField(choices=[(0, 'No sanctuary'), (1, 'Shrine'), (2, 'Sanctuary'), (3, 'Great Sanctuary')], default=0)),
                ('last_constructed_building_at', models.PositiveSmallIntegerField(default=0, help_text='Month the last building was commissioned, 0 if none was')),
                ('faction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='town', to='warband.faction')),
            ],
            options={
                'verbose_name': 'Town',
                'verbose_name_plural': 'Towns',
                'default_related_name': 'towns',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='Reason')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Faction')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('id',),
                'default_related_name': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('avatar_id', models.PositiveSmallIntegerField(default=1, verbose_name='Avatar-ID')),
                ('strength', models.PositiveSmallIntegerField(verbose_name='Strength')),
                ('strength_progress', models.PositiveSmallIntegerField(default=0, verbose_name='Strength progress')),
                ('strength_baseline', models.PositiveSmallIntegerField(verbose_name='Strength baseline')),
                ('stats_spread', models.PositiveSmallIntegerField(verbose_name='Stats spread')),
                ('stats_minimum', models.PositiveSmallIntegerField(verbose_name='Stats minimum')),
                ('nickname_variant', models.PositiveSmallIntegerField(default=0, verbose_name='Nickname variant')),
                ('dexterity', models.PositiveSmallIntegerField(verbose_name='Dexterity')),
                ('dexterity_progress', models.PositiveSmallIntegerField(default=0, verbose_name='Dexterity progress')),
                ('current_health', models.SmallIntegerField(verbose_name='Current health')),
                ('max_health', models.PositiveSmallIntegerField(verbose_name='Maximum health')),
                ('health_progress', models.PositiveSmallIntegerField(default=0, verbose_name='Health progress')),
                ('health_baseline', models.PositiveSmallIntegerField(verbose_name='Health baseline')),
                ('health_spread', models.PositiveSmallIntegerField(verbose_name='Health spread')),
                ('current_morale', models.SmallIntegerField(verbose_name='Current morale')),
                ('max_morale', models.PositiveSmallIntegerField(verbose_name='Maximum morale')),
                ('morale_progress', models.PositiveSmallIntegerField(default=0, verbose_name='Morale progress')),
                ('morale_baseline', models.PositiveSmallIntegerField(verbose_name='Morale baseline')),
                ('morale_spread', models.PositiveSmallIntegerField(verbose_name='Morale spread')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Experience')),
                ('monthly_salary', models.PositiveSmallIntegerField(default=0, verbose_name='Monthly salary')),
                ('unpaid_months', models.PositiveSmallIntegerField(default=0, verbose_name='Unpaid months')),
                ('recruitment_price', models.PositiveSmallIntegerField(default=0, verbose_name='Recruitment price')),
                ('is_pub_stock', models.BooleanField(default=False, verbose_name='Is pub stock')),
                ('last_used_skirmish_action', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance')], null=True)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'Healthy'), (2, 'Unconscious'), (3, 'Fleeing'), (4, 'Dead')], default=1, verbose_name='Condition')),
                ('armor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warrior_armor', to='warband.item', verbose_name='Armor')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.culture', verbose_name='Culture')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Faction')),
                ('savegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.savegame', verbose_name='Savegame')),
                ('weapon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warrior_weapon', to='warband.item', verbose_name='Weapon')),
            ],
            options={
                'verbose_name': 'Warrior',
                'verbose_name_plural': 'Warriors',
                'default_related_name': 'warriors',
            },
        ),
        migrations.CreateModel(
            name='SkirmishSpoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Item taken'), (2, 'Silver looted'), (3, 'Quest reward')], verbose_name='Kind')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Gaining faction')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warband.item', verbose_name='Item')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.skirmish', verbose_name='Skirmish')),
                ('warrior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warband.warrior', verbose_name='Taken from')),
            ],
            options={
                'verbose_name': 'Skirmish spoil',
                'verbose_name_plural': 'Skirmish spoils',
                'ordering': ('id',),
                'default_related_name': 'skirmish_spoils',
            },
        ),
        migrations.CreateModel(
            name='SkirmishBlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(verbose_name='Round')),
                ('attacker_action', models.PositiveSmallIntegerField(choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance')], verbose_name='Attacker action')),
                ('defender_action', models.PositiveSmallIntegerField(choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance')], verbose_name='Defender action')),
                ('outcome', models.PositiveSmallIntegerField(choices=[(1, 'Hit'), (2, 'Absorbed'), (3, 'Missed'), (4, 'Not thrown')], verbose_name='Outcome')),
                ('attack_dice', models.CharField(blank=True, max_length=10, verbose_name='Attack dice')),
                ('attack_modifier', models.SmallIntegerField(blank=True, null=True, verbose_name='Attack modifier')),
                ('attack_roll', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Attack roll')),
                ('attack_value', models.PositiveSmallIntegerField(default=0, verbose_name='Attack value')),
                ('defense_dice', models.CharField(max_length=10, verbose_name='Defense dice')),
                ('defense_modifier', models.SmallIntegerField(verbose_name='Defense modifier')),
                ('defense_roll', models.PositiveSmallIntegerField(verbose_name='Defense roll')),
                ('defense_value', models.PositiveSmallIntegerField(default=0, verbose_name='Defense value')),
                ('damage', models.PositiveSmallIntegerField(default=0, verbose_name='Damage')),
                ('attack_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blows_struck', to='warband.itemtype', verbose_name='Weapon type')),
                ('defense_item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blows_absorbed', to='warband.itemtype', verbose_name='Armor type')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.skirmish', verbose_name='Skirmish')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blows_dealt', to='warband.warrior', verbose_name='Attacker')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blows_taken', to='warband.warrior', verbose_name='Defender')),
            ],
            options={
                'verbose_name': 'Skirmish blow',
                'verbose_name_plural': 'Skirmish blows',
                'ordering': ('id',),
                'default_related_name': 'skirmish_blows',
            },
        ),
        migrations.AddField(
            model_name='skirmish',
            name='attacking_warriors',
            field=models.ManyToManyField(related_name='attacking_skirmishes', to='warband.warrior', verbose_name='Attacking warriors'),
        ),
        migrations.AddField(
            model_name='skirmish',
            name='defending_warriors',
            field=models.ManyToManyField(related_name='defending_skirmishes', to='warband.warrior', verbose_name='Defending warriors'),
        ),
        migrations.AddField(
            model_name='questcontract',
            name='assigned_warriors',
            field=models.ManyToManyField(to='warband.warrior', verbose_name='Assigned warriors'),
        ),
        migrations.AddField(
            model_name='faction',
            name='available_mercenaries',
            field=models.ManyToManyField(blank=True, related_name='available_pub_mercenaries', to='warband.warrior', verbose_name='Available mercenaries'),
        ),
        migrations.AddField(
            model_name='faction',
            name='captured_warriors',
            field=models.ManyToManyField(blank=True, to='warband.warrior', verbose_name='Captured warriors'),
        ),
        migrations.AddField(
            model_name='faction',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leading_factions', to='warband.warrior', verbose_name='Leader'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Weapon mastery'), (2, 'Swiftness'), (3, 'Shield wall')], verbose_name='Category')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Faction')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'default_related_name': 'trainings',
                'constraints': [models.UniqueConstraint(fields=('faction', 'category'), name='unique_faction_category')],
            },
        ),
        migrations.CreateModel(
            name='SkirmishWarriorGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gained_experience', models.PositiveIntegerField(default=0, verbose_name='Gained experience')),
                ('reached_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Reached level')),
                ('gained_strength', models.PositiveSmallIntegerField(default=0, verbose_name='Gained strength')),
                ('gained_dexterity', models.PositiveSmallIntegerField(default=0, verbose_name='Gained dexterity')),
                ('gained_max_health', models.PositiveSmallIntegerField(default=0, verbose_name='Gained maximum health')),
                ('gained_max_morale', models.PositiveSmallIntegerField(default=0, verbose_name='Gained maximum morale')),
                ('new_monthly_salary', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='New monthly salary')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Faction')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.skirmish', verbose_name='Skirmish')),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.warrior', verbose_name='Warrior')),
            ],
            options={
                'verbose_name': 'Skirmish warrior growth',
                'verbose_name_plural': 'Skirmish warrior growths',
                'ordering': ('id',),
                'default_related_name': 'skirmish_warrior_growths',
                'constraints': [models.UniqueConstraint(fields=('skirmish', 'warrior'), name='unique_growth_per_warrior_and_skirmish')],
            },
        ),
        migrations.CreateModel(
            name='SkirmishCasualty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fate', models.PositiveSmallIntegerField(choices=[(1, 'Fled the field'), (2, 'Knocked unconscious'), (3, 'Killed'), (4, 'Taken prisoner')], verbose_name='Fate')),
                ('skirmish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.skirmish', verbose_name='Skirmish')),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.warrior', verbose_name='Warrior')),
            ],
            options={
                'verbose_name': 'Skirmish casualty',
                'verbose_name_plural': 'Skirmish casualties',
                'ordering': ('id',),
                'default_related_name': 'skirmish_casualties',
                'constraints': [models.UniqueConstraint(fields=('skirmish', 'warrior'), name='unique_casualty_per_warrior_and_skirmish')],
            },
        ),
    ]
