# Generated by Django 6.1.1 on 2026-09-10 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0003_flee_as_a_skirmish_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Side he fought for'),
        ),
        migrations.AddField(
            model_name='battlehistory',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Narration'), (2, 'Warrior killed'), (3, 'Warrior knocked unconscious'), (4, 'Warrior left the field')], default=1, verbose_name='Kind'),
        ),
    ]
