# Generated by Django 6.1.1 on 2026-09-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0004_a_battle_log_line_knows_when_a_man_went_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlehistory',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Narration'), (2, 'Warrior killed'), (3, 'Warrior knocked unconscious'), (4, 'Warrior left the field'), (5, 'Round finished')], default=1, verbose_name='Kind'),
        ),
    ]
