# Generated by Django 6.1.1 on 2026-09-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0005_alter_battlehistory_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (9, 'Quests offered'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed'), (14, 'Morale lost over unpaid wages'), (15, 'Savegame ended'), (16, 'Rival defeated')], verbose_name='Kind'),
        ),
    ]
