# Generated by Django 6.1.1 on 2026-09-11 17:09

from django.db import migrations, models

from apps.warband.warrior.domain.attribute_draw import AttributeDraw
from apps.warband.warrior.services.nickname import draw_nickname_state

# How many warriors are held in memory at a time. SQLite caps a statement's parameters, and a
# bulk_update spends one per column per row, so the batch is well under what a single UPDATE may carry.
BACKFILL_BATCH_SIZE = 500


def freeze_every_warriors_epithet(apps, schema_editor):
    """
    Stamp every man already in a savegame with the epithet his attributes say he has.

    Correct for everybody who has not been levelled, trained, recruited out of a cell or caught by an
    incident since he was made; for everybody else this is the name he answers to today, and what he
    was called before it is not recorded anywhere.

    The rule comes from the service rather than a copy of it, so a savegame migrated now and a warrior
    generated now are decided the same way.

    Read and written in batches, the way the manager writes a whole roster: every warrior of every
    savegame is in scope here, which is more rows than any one thing in the game ever touches at once.
    """
    Warrior = apps.get_model("warband", "Warrior")
    batch = []

    for warrior in Warrior.objects.iterator(chunk_size=BACKFILL_BATCH_SIZE):
        warrior.nickname_state = draw_nickname_state(
            strength=AttributeDraw(
                value=warrior.strength,
                baseline=warrior.strength_baseline,
                spread=warrior.stats_spread,
                minimum=warrior.stats_minimum,
            ),
            dexterity=AttributeDraw(
                value=warrior.dexterity,
                baseline=warrior.strength_baseline,
                spread=warrior.stats_spread,
                minimum=warrior.stats_minimum,
            ),
            health=AttributeDraw(
                value=warrior.max_health, baseline=warrior.health_baseline, spread=warrior.health_spread
            ),
            morale=AttributeDraw(
                value=warrior.max_morale, baseline=warrior.morale_baseline, spread=warrior.morale_spread
            ),
        )
        batch.append(warrior)

        if len(batch) == BACKFILL_BATCH_SIZE:
            Warrior.objects.bulk_update(batch, ("nickname_state",))
            batch = []

    Warrior.objects.bulk_update(batch, ("nickname_state",))


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0006_a_month_log_line_says_a_rival_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='nickname_state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strength, past the near threshold'), (2, 'Strength, past the far threshold'), (3, 'Dexterity, past the near threshold'), (4, 'Dexterity, past the far threshold'), (5, 'Health, past the near threshold'), (6, 'Health, past the far threshold'), (7, 'Morale, past the near threshold'), (8, 'Morale, past the far threshold'), (9, 'Both arms at the floor'), (10, 'Health at the bottom'), (11, 'Morale at the bottom')], default=None, null=True, verbose_name='Nickname state'),
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (9, 'Quests offered'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed'), (14, 'Morale lost over unpaid wages'), (15, 'Savegame ended'), (16, 'Rival defeated'), (17, 'Nickname earned')], verbose_name='Kind'),
        ),
        # Nothing to undo: the column the backfill writes goes away with it
        migrations.RunPython(freeze_every_warriors_epithet, migrations.RunPython.noop),
    ]
