# Generated by Django 6.1.1 on 2026-09-14 10:30

from django.db import migrations, models

# The band each shipped type belongs to. Keyed on the name because that is what a database already
# holding the reference table has to be matched on, and this is the one place where keying on it is
# honest: it names the rows as they shipped, once, rather than deciding anything at generation time.
TIERS_BY_NAME = {
    "Pitchfork": 1,
    "Short sword": 1,
    "Spear": 1,
    "Studded leather": 1,
    "Battle axe": 2,
    "Long sword": 2,
    "Chain mail": 2,
}


def band_every_item_type(apps, schema_editor):
    """
    Put every type already in the database into the band the fixture now ships it in.

    An item generator draws from its tiers, so without this every pool resolves empty and warrior
    generation raises "No item type found." on the next savegame to ask for a man. The two fallbacks
    are left at null on purpose: they stand outside the bands rather than at the bottom of them.
    """
    ItemType = apps.get_model("warband", "ItemType")

    for name, tier in TIERS_BY_NAME.items():
        ItemType.objects.filter(name=name, is_fallback=False).update(tier=tier)


class Migration(migrations.Migration):

    dependencies = [
        ("warband", "0008_an_epithet_is_a_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="tier",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Rustic"), (2, "Fine")], default=None, null=True, verbose_name="Tier"
            ),
        ),
        # Nothing to undo: the column the backfill writes goes away with it
        migrations.RunPython(band_every_item_type, migrations.RunPython.noop),
    ]
