# Generated by Django 6.1.1 on 2026-09-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0009_gear_carries_a_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'default_related_name': 'training', 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.RemoveConstraint(
            model_name='training',
            name='unique_faction_category',
        ),
        migrations.AlterField(
            model_name='training',
            name='faction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Faction'),
        ),
    ]
