# Generated by Django 6.1.1 on 2026-09-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0010_a_faction_trains_by_one_regimen'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('attribute', models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity')], max_length=20, verbose_name='Attribute')),
                ('magnitude', models.PositiveSmallIntegerField(verbose_name='Magnitude')),
            ],
            options={
                'verbose_name': 'Injury type',
                'verbose_name_plural': 'Injury types',
                'default_related_name': 'injury_types',
            },
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (9, 'Quests offered'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed'), (14, 'Morale lost over unpaid wages'), (15, 'Savegame ended'), (16, 'Rival defeated'), (17, 'Nickname earned'), (18, 'Warrior injured')], verbose_name='Kind'),
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflicted_in_month', models.PositiveSmallIntegerField(verbose_name='Inflicted in month')),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.warrior', verbose_name='Warrior')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.injurytype', verbose_name='Injury type')),
            ],
            options={
                'verbose_name': 'Injury',
                'verbose_name_plural': 'Injuries',
                'ordering': ('id',),
                'default_related_name': 'injuries',
            },
        ),
    ]
