# Generated by Django 6.1.1 on 2026-09-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0011_a_beating_leaves_a_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skirmish',
            options={'default_related_name': 'skirmishes', 'ordering': ('id',), 'verbose_name': 'Skirmish', 'verbose_name_plural': 'Skirmishes'},
        ),
    ]
