# Generated by Django 6.1.1 on 2026-09-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0012_a_fight_says_how_it_sorts'),
    ]

    operations = [
        migrations.AddField(
            model_name='skirmish',
            name='fortification_strength',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fortification strength'),
        ),
        migrations.AlterField(
            model_name='skirmishblow',
            name='attacker_action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance'), (5, 'Flee'), (6, 'Assault the fortification')], verbose_name='Attacker action'),
        ),
        migrations.AlterField(
            model_name='skirmishblow',
            name='defender_action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance'), (5, 'Flee'), (6, 'Assault the fortification')], verbose_name='Defender action'),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='last_used_skirmish_action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance'), (5, 'Flee'), (6, 'Assault the fortification')], null=True),
        ),
    ]
