# Generated by Django 6.1.1 on 2026-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0014_a_quest_type_carries_a_fortification'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='fortification',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No fortification'), (1, 'Palisade'), (2, 'Earthwork'), (3, 'Burh Wall')], default=0),
        ),
    ]
