# Generated by Django 6.1.1 on 2026-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0015_a_town_raises_a_wall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skirmishblow',
            name='attacker_action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance'), (5, 'Flee'), (6, 'Assault the fortification'), (7, 'Rally the men')], verbose_name='Attacker action'),
        ),
        migrations.AlterField(
            model_name='skirmishblow',
            name='defender_action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance'), (5, 'Flee'), (6, 'Assault the fortification'), (7, 'Rally the men')], verbose_name='Defender action'),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='last_used_skirmish_action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Simple attack'), (2, 'Risky attack'), (3, 'Fast attack'), (4, 'Defensive stance'), (5, 'Flee'), (6, 'Assault the fortification'), (7, 'Rally the men')], null=True),
        ),
    ]
