# Generated by Django 6.1.1 on 2026-09-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0016_a_leader_rallies_his_men'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Month')),
                ('incident', models.CharField(max_length=50, verbose_name='Incident')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(blank=True, default='', verbose_name='Body')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.faction', verbose_name='Faction')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warband.item', verbose_name='Item')),
                ('rival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_incidents_as_rival', to='warband.faction', verbose_name='Rival')),
            ],
            options={
                'verbose_name': 'Pending incident',
                'verbose_name_plural': 'Pending incidents',
                'ordering': ('id',),
                'default_related_name': 'pending_incidents',
            },
        ),
    ]
