# Generated by Django 6.1.1 on 2026-09-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0017_an_incident_asks_a_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='saga',
            field=models.TextField(blank=True, default='', verbose_name='Saga'),
        ),
    ]
