# Generated by Django 6.1.1 on 2026-09-27 08:57

import django.db.models.deletion
from django.db import migrations, models


def snapshot_every_item_spoil(apps, schema_editor):
    """
    Write the name and dice of every spoil whose item is still there.

    Spells out "Item.display_name" and the dice string by hand, because a historical model carries the
    fields and none of the properties. Every item spoil in the database still has its item at this
    point: the relation only starts letting go of a deleted one with this migration.
    """
    SkirmishSpoil = apps.get_model("warband", "SkirmishSpoil")
    batch = []

    for spoil in SkirmishSpoil.objects.filter(item__isnull=False).select_related("item__type"):
        item = spoil.item
        modifier = f"+{item.modifier}" if item.modifier >= 0 else f"{item.modifier}"

        spoil.item_name = item.type.name if item.type.is_fallback else f"{item.get_condition_display()} {item.type.name}"
        spoil.item_dice = f"{item.type.base_value}{modifier}"
        batch.append(spoil)

    SkirmishSpoil.objects.bulk_update(batch, ["item_name", "item_dice"])


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0018_a_fight_is_told_as_a_saga'),
    ]

    operations = [
        migrations.AddField(
            model_name='skirmishspoil',
            name='item_dice',
            field=models.CharField(blank=True, max_length=20, verbose_name='Item dice'),
        ),
        migrations.AddField(
            model_name='skirmishspoil',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='skirmishspoil',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warband.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='armor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warrior_armor', to='warband.item', verbose_name='Armor'),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warrior_weapon', to='warband.item', verbose_name='Weapon'),
        ),
        migrations.RunPython(snapshot_every_item_spoil, migrations.RunPython.noop),
    ]
