# Generated by Django 6.1.1 on 2026-09-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0020_a_feast_mends_a_broken_nerve'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('hook', models.SlugField(max_length=30, unique=True, verbose_name='Hook')),
                ('group', models.SlugField(max_length=30, verbose_name='Group')),
                ('attribute', models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity')], max_length=20, verbose_name='Attribute')),
                ('magnitude', models.SmallIntegerField(verbose_name='Magnitude')),
                ('source', models.CharField(choices=[('innate', 'Innate'), ('earned', 'Earned')], max_length=10, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Trait type',
                'verbose_name_plural': 'Trait types',
                'ordering': ('id',),
                'default_related_name': 'trait_types',
            },
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (9, 'Quests offered'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed'), (14, 'Morale lost over unpaid wages'), (15, 'Savegame ended'), (16, 'Rival defeated'), (17, 'Nickname earned'), (18, 'Warrior injured'), (19, 'Feast thrown'), (20, 'Warrior changed')], verbose_name='Kind'),
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.warrior', verbose_name='Warrior')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warband.traittype', verbose_name='Trait type')),
            ],
            options={
                'verbose_name': 'Trait',
                'verbose_name_plural': 'Traits',
                'ordering': ('id',),
                'default_related_name': 'traits',
                'constraints': [models.UniqueConstraint(fields=('warrior', 'type'), name='trait_once_per_warrior')],
            },
        ),
    ]
