# Generated by Django 6.1.1 on 2026-09-27 13:49

import apps.warband.calendar.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0021_a_man_has_a_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegame',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=apps.warband.calendar.date.draw_start_year, verbose_name='Start year'),
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (9, 'Quests offered'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed'), (14, 'Morale lost over unpaid wages'), (15, 'Savegame ended'), (16, 'Rival defeated'), (17, 'Nickname earned'), (18, 'Warrior injured'), (19, 'Feast thrown'), (20, 'Warrior changed'), (21, 'Harvest')], verbose_name='Kind'),
        ),
    ]
