# Generated by Django 6.1.1 on 2026-09-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0022_the_year_has_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrior',
            name='nickname_state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Strength, past the near threshold'), (2, 'Strength, past the far threshold'), (3, 'Dexterity, past the near threshold'), (4, 'Dexterity, past the far threshold'), (5, 'Health, past the near threshold'), (6, 'Health, past the far threshold'), (7, 'Morale, past the near threshold'), (8, 'Morale, past the far threshold'), (9, 'Both arms at the bottom'), (10, 'Health at the bottom'), (11, 'Morale at the bottom')], default=None, null=True, verbose_name='Nickname state'),
        ),
    ]
