# Generated by Django 6.1.1 on 2026-09-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0023_feeble_arms_are_read_as_a_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('hex', models.CharField(max_length=7, verbose_name='Hex')),
            ],
            options={
                'verbose_name': 'Hair colour',
                'verbose_name_plural': 'Hair colours',
                'ordering': ('id',),
                'default_related_name': 'hair_colours',
            },
        ),
        migrations.RemoveField(
            model_name='warrior',
            name='avatar_id',
        ),
        migrations.AddField(
            model_name='warrior',
            name='beard_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warriors_with_beard_colour', to='warband.haircolour', verbose_name='Beard colour'),
        ),
        migrations.AddField(
            model_name='warrior',
            name='hair_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warriors_with_hair_colour', to='warband.haircolour', verbose_name='Hair colour'),
        ),
        migrations.CreateModel(
            name='PortraitPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('face', 'Face'), ('hair', 'Hair'), ('beard', 'Beard')], max_length=10, verbose_name='Kind')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number')),
                ('image', models.CharField(max_length=100, verbose_name='Image')),
                ('left', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Left')),
                ('top', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Top')),
                ('width', models.DecimalField(decimal_places=4, default=1, max_digits=5, verbose_name='Width')),
            ],
            options={
                'verbose_name': 'Portrait piece',
                'verbose_name_plural': 'Portrait pieces',
                'ordering': ('kind', 'number'),
                'default_related_name': 'portrait_pieces',
                'constraints': [models.UniqueConstraint(fields=('kind', 'number'), name='unique_portrait_piece_number')],
            },
        ),
        migrations.AddField(
            model_name='warrior',
            name='portrait_beard',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'beard'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warriors_with_beard', to='warband.portraitpiece', verbose_name='Beard'),
        ),
        migrations.AddField(
            model_name='warrior',
            name='portrait_face',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'face'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warriors_with_face', to='warband.portraitpiece', verbose_name='Face'),
        ),
        migrations.AddField(
            model_name='warrior',
            name='portrait_hair',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'hair'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warriors_with_hair', to='warband.portraitpiece', verbose_name='Hair'),
        ),
    ]
