# Generated by Django 6.1.1 on 2026-09-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0025_period_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='renown',
            field=models.PositiveIntegerField(default=0, verbose_name='Renown'),
        ),
    ]
