# Generated by Django 6.1.1 on 2026-09-30 11:23

import django.db.models.deletion
from django.db import migrations, models


def record_every_attacking_leader(apps, schema_editor):
    """
    Name the attacking leader of every fight he stood in.

    Read off "attacking_faction.leader" as it is now, because nothing else records who led a fight. A
    fight whose leader has since been succeeded is left unnamed: the man now in the seat did not lead
    it, and the one who did can no longer be told apart from the rest of its roster.
    """
    Skirmish = apps.get_model("warband", "Skirmish")
    batch = []

    for skirmish in Skirmish.objects.filter(attacking_faction__leader__isnull=False).select_related(
        "attacking_faction"
    ):
        leader_id = skirmish.attacking_faction.leader_id
        if skirmish.attacking_warriors.filter(id=leader_id).exists():
            skirmish.attacking_leader_id = leader_id
            batch.append(skirmish)

    Skirmish.objects.bulk_update(batch, ["attacking_leader"])


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0027_a_new_man_takes_the_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='skirmish',
            name='attacking_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_skirmishes', to='warband.warrior', verbose_name='Attacking leader'),
        ),
        migrations.RunPython(record_every_attacking_leader, migrations.RunPython.noop),
    ]
