# Generated by Django 6.1.1 on 2026-10-01 04:24

from django.db import migrations, models


def start_every_wall_where_it_stands(apps, schema_editor):
    """
    Give every fight a starting wall.

    Nothing recorded what a wall began at, so the wall as it stands now is the most that can be said. For a
    fight that is over or never had a wall that is all there is to it; one still being fought reads as
    untouched until it ends.
    """
    Skirmish = apps.get_model("warband", "Skirmish")
    Skirmish.objects.update(starting_fortification_strength=models.F("fortification_strength"))


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0028_a_fight_remembers_who_led_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='skirmish',
            name='starting_fortification_strength',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Starting fortification strength'),
        ),
        migrations.RunPython(start_every_wall_where_it_stands, migrations.RunPython.noop),
    ]
