# Generated by Django 6.1.1 on 2026-10-02 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0031_a_full_cell_lets_a_captive_go'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leading_factions', to='warband.warrior', verbose_name='Ealdorman'),
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (9, 'Quests offered'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed'), (14, 'Morale lost over unpaid wages'), (15, 'Savegame ended'), (16, 'Rival defeated'), (17, 'Nickname earned'), (18, 'Warrior injured'), (19, 'Feast thrown'), (20, 'Warrior changed'), (21, 'Harvest'), (22, 'Ealdorman succeeded'), (23, 'Ealdorman raised from the fyrd'), (24, 'Captive fled')], verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='skirmish',
            name='attacking_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_skirmishes', to='warband.warrior', verbose_name='Attacking Ealdorman'),
        ),
    ]
