# Generated by Django 6.1.1 on 2026-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0034_a_leader_is_never_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='skirmish',
            name='raid_kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lift the herds'), (2, 'Burn the village'), (3, 'Storm the burh')], default=3, verbose_name='Raid kind'),
        ),
        migrations.AlterField(
            model_name='skirmishspoil',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Item taken'), (2, 'Silver looted'), (3, 'Herds lifted'), (4, 'Village burned')], verbose_name='Kind'),
        ),
    ]
