# Generated by Django 6.1.1 on 2026-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0035_a_march_is_one_of_three_raids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingincident',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
