# Generated by Django 6.1.1 on 2026-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0037_every_rival_town_has_its_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='skirmish',
            name='local_warriors',
            field=models.ManyToManyField(blank=True, related_name='local_skirmishes', to='warband.warrior', verbose_name='Local warriors'),
        ),
    ]
