# Generated by Django 6.1.1 on 2026-10-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0038_the_people_of_a_place_turn_out_to_defend_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthlog',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags'),
        ),
    ]
