# Generated by Django 6.1.1 on 2026-10-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0038_the_people_of_a_place_turn_out_to_defend_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='last_tended_at',
            field=models.PositiveSmallIntegerField(default=0, help_text='Month his wounds were last tended for silver, 0 if never', verbose_name='Last tended at'),
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed'), (14, 'Morale lost over unpaid wages'), (15, 'Savegame ended'), (16, 'Rival defeated'), (17, 'Nickname earned'), (18, 'Warrior injured'), (19, 'Feast thrown'), (20, 'Warrior changed'), (21, 'Harvest'), (22, 'Ealdorman succeeded'), (23, 'Ealdorman raised from the fyrd'), (24, 'Captive fled'), (25, 'Quest returned'), (26, 'Wounds tended')], verbose_name='Kind'),
        ),
    ]
