# Generated by Django 6.1.1 on 2026-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warband', '0040_silver_tends_a_wounded_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='last_geld_at',
            field=models.PositiveSmallIntegerField(default=0, help_text='Month the last geld was called on the village, 0 if none was'),
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior walked out'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident'), (13, 'Warrior dismissed'), (14, 'Morale lost over unpaid wages'), (15, 'Savegame ended'), (16, 'Rival defeated'), (17, 'Nickname earned'), (18, 'Warrior injured'), (19, 'Feast thrown'), (20, 'Warrior changed'), (21, 'Harvest'), (22, 'Ealdorman succeeded'), (23, 'Ealdorman raised from the fyrd'), (24, 'Captive fled'), (25, 'Quest returned'), (26, 'Wounds tended'), (27, 'Geld called')], verbose_name='Kind'),
        ),
    ]
