# Generated by Django 5.2 on 2025-08-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("faction", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hall",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Mead Hall"), (2, "Great Hall"), (3, "High Hall")],
                        default=1,
                    ),
                ),
                (
                    "weaponsmith",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Smithy"), (2, "Forge Hall"), (3, "Master Forge")],
                        default=1,
                    ),
                ),
                (
                    "marketplace",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Market place"),
                            (2, "Trading post"),
                            (3, "High market"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "sanctuary",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Shrine"),
                            (2, "Sanctuary"),
                            (3, "Great Sanctuary"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "faction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faction.faction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Town",
                "verbose_name_plural": "Towns",
                "default_related_name": "towns",
            },
        ),
    ]
