# Generated by Django 5.2 on 2025-08-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0002_initial"),
        ("town", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="town",
            name="faction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="town",
                to="faction.faction",
            ),
        ),
        migrations.AlterField(
            model_name="town",
            name="hall",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No hall"),
                    (1, "Mead Hall"),
                    (2, "Great Hall"),
                    (3, "High Hall"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="town",
            name="marketplace",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No market place"),
                    (1, "Market place"),
                    (2, "Trading post"),
                    (3, "High market"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="town",
            name="sanctuary",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No sanctuary"),
                    (1, "Shrine"),
                    (2, "Sanctuary"),
                    (3, "Great Sanctuary"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="town",
            name="weaponsmith",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No weaponsmith"),
                    (1, "Smithy"),
                    (2, "Forge Hall"),
                    (3, "Master Forge"),
                ],
                default=0,
            ),
        ),
    ]
