# Generated by Django 5.2 on 2025-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("town", "0002_alter_town_faction_alter_town_hall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="town",
            name="last_constructed_building_at",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Month the last building was commissioned"
            ),
        ),
    ]
