# Generated by Django 5.2.16 on 2026-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('town', '0003_town_last_constructed_building_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='last_constructed_building_at',
            field=models.PositiveSmallIntegerField(default=0, help_text='Month the last building was commissioned, 0 if none was'),
        ),
    ]
