# Generated by Django 5.2.16 on 2026-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("town", "0005_create_missing_towns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="town",
            name="marketplace",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "No marketplace"), (1, "Marketplace"), (2, "Trading Post"), (3, "High Market")], default=0
            ),
        ),
    ]
