"""
Django settings for tettenhall project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import datetime
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
APPS_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-u%gv-czfihlp%e7@mae9lu*i)$d14piy@jh+0$-8e%n1+b8kub"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "crispy_bootstrap5",
    "apps.account",
    "apps.common",
    "apps.faction",
    "apps.finance",
    "apps.incident",
    "apps.item",
    "apps.quest",
    "apps.savegame",
    "apps.skirmish",
    "apps.town",
    "apps.training",
    "apps.warrior",
    "apps.month",
    "axes",
]

if DEBUG:
    INSTALLED_APPS += ["django_removals"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # AxesMiddleware should be the last middleware in the MIDDLEWARE list.
    "axes.middleware.AxesMiddleware",
]

AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    "axes.backends.AxesBackend",
    # Django ModelBackend is the default authentication backend.
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "account:login-view"

ROOT_URLCONF = "apps.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Custom
                "apps.finance.context_processors.get_current_balance",
                "apps.savegame.context_processors.current_savegame.current_savegame",
                "apps.skirmish.context_processors.get_open_skirmishes",
                "apps.warrior.context_processors.get_current_amount_warriors",
            ],
        },
    },
]

WSGI_APPLICATION = "apps.config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Additional locations of static files
STATICFILES_DIRS = (
    str(BASE_DIR) + "/node_modules/",
    str(BASE_DIR) + "/static/",
)


# Crispy forms
# django-crispy-forms ships no template pack of its own; the pack is a separate distribution.
# The site's own styling is UIkit, applied through the "uk-*" classes the FormHelper layouts set
# on the fields, so the pack only supplies the surrounding markup.
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Axes config
def axes_cooloff_time(request) -> datetime.timedelta:  # noqa: PBR001
    # Ruff:E731 prevents assignment of lambda expression -> function required
    return datetime.timedelta(0, LOGIN_TIMEDELTA)


LOGIN_TIMEDELTA = 15 * 60
LOGIN_COUNT = 3
AXES_COOLOFF_TIME = axes_cooloff_time
AXES_LOCKOUT_TEMPLATE = "account/login_lockout.html"
AXES_LOGIN_FAILURE_LIMIT = LOGIN_COUNT
AXES_USERNAME_FORM_FIELD = "username"
AXES_CLEANUP_DAYS = 30
# Block by Username only (i.e.: Same user different IP is still blocked, but different user same IP is not)
AXES_LOCKOUT_PARAMETERS = ["username"]
# Disable logging the IP-Address of failed login attempts by returning None for attempts to get the IP
AXES_CLIENT_IP_CALLABLE = lambda x: None  # noqa: E731
# Mask user-sensitive parameters in logging stream
AXES_SENSITIVE_PARAMETERS = ["username", "ip_address"]
# axes.W006 asks for "ip_address" in AXES_LOCKOUT_PARAMETERS. AXES_CLIENT_IP_CALLABLE hands axes
# None for every request, so the parameter would group all attempts into a single bucket rather
# than rate-limit anyone.
SILENCED_SYSTEM_CHECKS = ["axes.W006"]

# Queuebie
# Queuebie treats every app below this path as a local one and imports its "handlers/" modules.
# Pointing it at BASE_DIR would include everything in ".venv/", which uv creates inside the project,
# so a dependency shipping a "handlers/commands/" directory would register handlers on our bus.
QUEUEBIE_APP_BASE_PATH = BASE_DIR / "apps"
QUEUEBIE_STRICT_MODE = True
# Named here rather than left to queuebie's own default, so the logger this project configures below
# and the one the bus writes to cannot drift apart.
QUEUEBIE_LOGGER_NAME = "queuebie"


# Logging
# https://docs.djangoproject.com/en/stable/topics/logging/
# Django configures its own "django" logger and nothing else, so any other logger propagates to a
# root logger with no handler and falls back to "logging.lastResort", which drops everything below
# WARNING. One console handler for the whole project, on the root logger.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "{asctime} {levelname:<7} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        # Django applies its own config first and gives this logger a console handler of its own,
        # without turning propagation off, so leaving it alone would print every Django record
        # twice - once there and once on the root handler. It keeps its level and loses its
        # handler, which also drops "mail_admins" from the chain: the project configures neither
        # ADMINS nor a mail backend, so nothing was ever sent.
        # Naming it here also resets every logger below it - "django.server" and "django.request" -
        # to no handler of its own and propagation on, which is what "logging.config" does to the
        # children of a configured logger. So the runserver request lines arrive in the format
        # below rather than in Django's own "[server_time] message", and every Django record
        # reaches the console through the one handler.
        "django": {
            "handlers": [],
            "level": "INFO" if DEBUG else "WARNING",
        },
        # The bus narrates itself: one line per message drained, naming the handler it goes to, and
        # one for the messages that handler returned. That is the record of an ordering question -
        # which is otherwise answered by reading "queuebie/runner.py" - so it is on in development.
        QUEUEBIE_LOGGER_NAME: {
            "level": "DEBUG" if DEBUG else "WARNING",
        },
    },
}


# Hide development server warning
# https://docs.djangoproject.com/en/stable/ref/django-admin/#envvar-DJANGO_RUNSERVER_HIDE_WARNING
# setdefault, not assignment: this runs in every process importing the settings, and an operator who
# set the variable deliberately - or who wants the warning - should win over an import side effect
os.environ.setdefault("DJANGO_RUNSERVER_HIDE_WARNING", "true")
