"""
The Gaelic name stock the provider draws from.

Orthography, applied to every entry below without exception:

- **Old Irish forms, not their modern descendants.** "Diarmait", not the Modern Irish "Diarmaid";
  "Domnall", not "Donal"; "Muirchertach", not "Murtagh". The game stands in 910, and the anglicised
  half of Faker's own Irish name data is right for the twentieth century and wrong for this one.
- **The length mark is written.** "Aed" and "Áed" are two different words, so the acute stays wherever
  the vowel is long, the way every scholarly edition of the annals prints it. Nothing else is outside
  ASCII: no manuscript abbreviation and no lenition dot - lenition is written with an "h", which is
  what the provider's joining rules do.
- **No "Ó" and no "Mac".** Both build a surname out of an ancestor, and what a warrior is drawn is a
  given name. In 910 neither particle is yet the fixed hereditary marker it later becomes.
- **One word per name.** The two-element names - "Máel Sechnaill", "Gilla Críst" - are left out
  deliberately: it is the second element that inflects, so a place name built on one runs to four
  words and reads as a sentence rather than as a settlement.

Every name carries its genitive, because the genitive is what a place name is built on and Old Irish
does not let it be derived. Five stem classes are in play and which one a name belongs to cannot be
read off its nominative: "Cormac" gives "Cormaic", "Áed" gives "Áeda", "Óengus" gives "Óengusa" and
"Niall" gives "Néill". A rule would be wrong for a third of the pool, so the inflection sits in the
data here and only the compositional rules - lenition, and which generic triggers it - are code.

Place names put the generic first and inflect what follows it, which is the Irish order rather than
the English one: "Cill Chiaráin", not a compound. A generic therefore carries its grammatical gender,
because a feminine one lenites whatever follows and a masculine one does not.
"""

from typing import NamedTuple

# A generic's gender, which inside a place name has exactly one consequence: whether the word after it
# is lenited. Spelled out rather than carried as a boolean, because the gender is the fact and the
# lenition is what follows from it.
FEMININE = "f"
MASCULINE = "m"


class GivenName(NamedTuple):
    nominative: str
    genitive: str


class PlaceGeneric(NamedTuple):
    word: str
    gender: str


# Male given names, out of the annals and the genealogies. The "-án" diminutives and the "-ach"
# adjectival names dominate because they dominate the record, which is also what keeps a war band
# reading as a war band: the pool recombines a small stock of elements the way the families did.
GIVEN_NAMES = (
    GivenName("Áed", "Áeda"),
    GivenName("Áedán", "Áedáin"),
    GivenName("Ailbe", "Ailbi"),
    GivenName("Ailill", "Ailello"),
    GivenName("Ainmire", "Ainmerech"),
    GivenName("Airechtach", "Airechtaig"),
    GivenName("Airmedach", "Airmedaig"),
    GivenName("Amalgaid", "Amalgada"),
    GivenName("Anluan", "Anluain"),
    GivenName("Artgal", "Artgail"),
    GivenName("Artúr", "Artúir"),
    GivenName("Baetán", "Baetáin"),
    GivenName("Baíthéne", "Baíthéni"),
    GivenName("Bécán", "Bécáin"),
    GivenName("Blathmac", "Blathmaic"),
    GivenName("Bran", "Brain"),
    GivenName("Branán", "Branáin"),
    GivenName("Brandub", "Branduib"),
    GivenName("Brecc", "Bricc"),
    GivenName("Bresal", "Bresail"),
    GivenName("Brian", "Briain"),
    GivenName("Broccán", "Broccáin"),
    GivenName("Bróen", "Bróin"),
    GivenName("Buadach", "Buadaig"),
    GivenName("Cairell", "Cairill"),
    GivenName("Cairpre", "Cairpri"),
    GivenName("Canannán", "Canannáin"),
    GivenName("Cathal", "Cathail"),
    GivenName("Cathalán", "Cathaláin"),
    GivenName("Cathasach", "Cathasaig"),
    GivenName("Cathbarr", "Cathbairr"),
    GivenName("Ceithernach", "Ceithernaig"),
    GivenName("Cellach", "Cellaig"),
    GivenName("Cellachán", "Cellacháin"),
    GivenName("Cellán", "Celláin"),
    GivenName("Cerball", "Cerbaill"),
    GivenName("Cernach", "Cernaig"),
    GivenName("Cian", "Céin"),
    GivenName("Cianán", "Cianáin"),
    GivenName("Ciarán", "Ciaráin"),
    GivenName("Cináed", "Cináeda"),
    GivenName("Clérech", "Clérig"),
    GivenName("Cobthach", "Cobthaig"),
    GivenName("Coibdenach", "Coibdenaig"),
    GivenName("Colgu", "Colgan"),
    GivenName("Colmán", "Colmáin"),
    GivenName("Colum", "Coluim"),
    GivenName("Comaltán", "Comaltáin"),
    GivenName("Comgall", "Comgaill"),
    GivenName("Comgán", "Comgáin"),
    GivenName("Conaire", "Conairi"),
    GivenName("Conall", "Conaill"),
    GivenName("Conchobar", "Conchobair"),
    GivenName("Congal", "Congail"),
    GivenName("Congalach", "Congalaig"),
    GivenName("Conn", "Cuinn"),
    GivenName("Connmach", "Connmaig"),
    GivenName("Corcrán", "Corcráin"),
    GivenName("Cormac", "Cormaic"),
    GivenName("Crimthann", "Crimthainn"),
    GivenName("Crónán", "Crónáin"),
    GivenName("Crundmáel", "Crundmaíl"),
    GivenName("Cuán", "Cuáin"),
    GivenName("Cuilennán", "Cuilennáin"),
    GivenName("Cummascach", "Cummascaig"),
    GivenName("Curnán", "Curnáin"),
    GivenName("Dallán", "Dalláin"),
    GivenName("Diarmait", "Diarmata"),
    GivenName("Dinertach", "Dinertaig"),
    GivenName("Díumasach", "Díumasaig"),
    GivenName("Dochartach", "Dochartaig"),
    GivenName("Domangart", "Domangairt"),
    GivenName("Domnall", "Domnaill"),
    GivenName("Donn", "Duinn"),
    GivenName("Donnacán", "Donnacáin"),
    GivenName("Donnán", "Donnáin"),
    GivenName("Donnchad", "Donnchaid"),
    GivenName("Donngal", "Donngail"),
    GivenName("Donngus", "Donngusa"),
    GivenName("Dub", "Duib"),
    GivenName("Dubán", "Dubáin"),
    GivenName("Dubgall", "Dubgaill"),
    GivenName("Dubthach", "Dubthaig"),
    GivenName("Dúnadach", "Dúnadaig"),
    GivenName("Dúnchad", "Dúnchaid"),
    GivenName("Dúngal", "Dúngail"),
    GivenName("Dúnlang", "Dúnlainge"),
    GivenName("Écertach", "Écertaig"),
    GivenName("Echmarcach", "Echmarcaig"),
    GivenName("Éicnechán", "Éicnecháin"),
    GivenName("Éladach", "Éladaig"),
    GivenName("Eochaid", "Echdach"),
    GivenName("Eógan", "Eógain"),
    GivenName("Erc", "Eirc"),
    GivenName("Ernán", "Ernáin"),
    GivenName("Fáelán", "Fáeláin"),
    GivenName("Fáelchad", "Fáelchaid"),
    GivenName("Fáelchú", "Fáelchon"),
    GivenName("Faílbe", "Faílbi"),
    GivenName("Feradach", "Feradaig"),
    GivenName("Ferchar", "Ferchair"),
    GivenName("Ferdálach", "Ferdálaig"),
    GivenName("Ferdomnach", "Ferdomnaig"),
    GivenName("Fergal", "Fergail"),
    GivenName("Fergus", "Fergusa"),
    GivenName("Fiachna", "Fiachnae"),
    GivenName("Fiachra", "Fiachrach"),
    GivenName("Fiangalach", "Fiangalaig"),
    GivenName("Fínán", "Fínáin"),
    GivenName("Finnacán", "Finnacáin"),
    GivenName("Finnbarr", "Finnbairr"),
    GivenName("Fintan", "Fintain"),
    GivenName("Flaithbertach", "Flaithbertaig"),
    GivenName("Flann", "Flainn"),
    GivenName("Flannacán", "Flannacáin"),
    GivenName("Flannán", "Flannáin"),
    GivenName("Flannchad", "Flannchaid"),
    GivenName("Fogartach", "Fogartaig"),
    GivenName("Follamán", "Follamáin"),
    GivenName("Forbasach", "Forbasaig"),
    GivenName("Forindán", "Forindáin"),
    GivenName("Fothad", "Fothaid"),
    GivenName("Fráech", "Fraích"),
    GivenName("Furudrán", "Furudráin"),
    GivenName("Garbán", "Garbáin"),
    GivenName("Glaisne", "Glaisni"),
    GivenName("Gorman", "Gormain"),
    GivenName("Gormgal", "Gormgail"),
    GivenName("Gúaire", "Gúairi"),
    GivenName("Gussán", "Gussáin"),
    GivenName("Indrechtach", "Indrechtaig"),
    GivenName("Írgalach", "Írgalaig"),
    GivenName("Lachtnán", "Lachtnáin"),
    GivenName("Laidcnén", "Laidcnéin"),
    GivenName("Lasrén", "Lasréin"),
    GivenName("Lethlobar", "Lethlobair"),
    GivenName("Loarn", "Loairn"),
    GivenName("Loingsech", "Loingsig"),
    GivenName("Lonán", "Lonáin"),
    GivenName("Lorcán", "Lorcáin"),
    GivenName("Lugaid", "Lugdach"),
    GivenName("Máelán", "Máeláin"),
    GivenName("Manchán", "Mancháin"),
    GivenName("Marcachán", "Marcacháin"),
    GivenName("Marcán", "Marcáin"),
    GivenName("Mathgamain", "Mathgamna"),
    GivenName("Míadach", "Míadaig"),
    GivenName("Míadachán", "Míadacháin"),
    GivenName("Móenach", "Móenaig"),
    GivenName("Mongán", "Mongáin"),
    GivenName("Mórán", "Móráin"),
    GivenName("Mugrón", "Mugróin"),
    GivenName("Muirchertach", "Muirchertaig"),
    GivenName("Muirchú", "Muirchon"),
    GivenName("Muirecán", "Muirecáin"),
    GivenName("Muiredach", "Muiredaig"),
    GivenName("Muirgius", "Muirgiusa"),
    GivenName("Murchad", "Murchaid"),
    GivenName("Nechtan", "Nechtain"),
    GivenName("Niall", "Néill"),
    GivenName("Nuadu", "Nuadat"),
    GivenName("Óengus", "Óengusa"),
    GivenName("Ólchobar", "Ólchobair"),
    GivenName("Onchú", "Onchon"),
    GivenName("Orthanach", "Orthanaig"),
    GivenName("Rechtgal", "Rechtgail"),
    GivenName("Rígbardán", "Rígbardáin"),
    GivenName("Robartach", "Robartaig"),
    GivenName("Rónán", "Rónáin"),
    GivenName("Rothechtach", "Rothechtaig"),
    GivenName("Ruadacán", "Ruadacáin"),
    GivenName("Ruadán", "Ruadáin"),
    GivenName("Ruaidrí", "Ruaidrí"),
    GivenName("Rumann", "Rumainn"),
    GivenName("Scandlán", "Scandláin"),
    GivenName("Scannal", "Scannail"),
    GivenName("Scellán", "Scelláin"),
    GivenName("Sechnasach", "Sechnasaig"),
    GivenName("Segéne", "Segéni"),
    GivenName("Selbach", "Selbaig"),
    GivenName("Senán", "Senáin"),
    GivenName("Sillán", "Silláin"),
    GivenName("Sinchell", "Sinchill"),
    GivenName("Sléibéne", "Sléibéni"),
    GivenName("Sluagadach", "Sluagadaig"),
    GivenName("Snédgus", "Snédgusa"),
    GivenName("Sóergus", "Sóergusa"),
    GivenName("Suairlech", "Suairlig"),
    GivenName("Suibne", "Suibni"),
    GivenName("Tadg", "Taidg"),
    GivenName("Tigernach", "Tigernaig"),
    GivenName("Tigernán", "Tigernáin"),
    GivenName("Tipraite", "Tipraiti"),
    GivenName("Tnúthgal", "Tnúthgail"),
    GivenName("Toicthech", "Toicthig"),
    GivenName("Tomaltach", "Tomaltaig"),
    GivenName("Tressach", "Tressaig"),
    GivenName("Tuathal", "Tuathail"),
    GivenName("Uaithne", "Uaithni"),
    GivenName("Ualgarg", "Ualgairg"),
    GivenName("Uargalach", "Uargalaig"),
    GivenName("Ultán", "Ultáin"),
)

# What a settlement is: the first word of the name, and the one that decides whether the second is
# lenited. The gender is the word's own rather than a choice - "cill" is feminine and "dún" is
# masculine, and a place name that gets either wrong is misspelled rather than differently spelled.
PLACE_GENERICS = (
    PlaceGeneric("Achad", MASCULINE),
    PlaceGeneric("Ard", MASCULINE),
    PlaceGeneric("Áth", MASCULINE),
    PlaceGeneric("Baile", MASCULINE),
    PlaceGeneric("Belach", MASCULINE),
    PlaceGeneric("Caisel", MASCULINE),
    PlaceGeneric("Carraig", FEMININE),
    PlaceGeneric("Cill", FEMININE),
    PlaceGeneric("Cluain", FEMININE),
    PlaceGeneric("Cnoc", MASCULINE),
    PlaceGeneric("Coill", FEMININE),
    PlaceGeneric("Cúil", FEMININE),
    PlaceGeneric("Doire", MASCULINE),
    PlaceGeneric("Domnach", MASCULINE),
    PlaceGeneric("Druim", MASCULINE),
    PlaceGeneric("Dún", MASCULINE),
    PlaceGeneric("Glais", FEMININE),
    PlaceGeneric("Gleann", MASCULINE),
    PlaceGeneric("Inis", FEMININE),
    PlaceGeneric("Léim", FEMININE),
    PlaceGeneric("Lios", MASCULINE),
    PlaceGeneric("Loch", MASCULINE),
    PlaceGeneric("Mag", MASCULINE),
    PlaceGeneric("Muine", MASCULINE),
    PlaceGeneric("Port", MASCULINE),
    PlaceGeneric("Ráth", FEMININE),
    PlaceGeneric("Sliab", MASCULINE),
    PlaceGeneric("Sruthair", FEMININE),
    PlaceGeneric("Tír", MASCULINE),
    PlaceGeneric("Tobar", MASCULINE),
    PlaceGeneric("Tuaim", FEMININE),
    PlaceGeneric("Tulach", FEMININE),
)

# Adjectives a generic can be qualified by. None of them is also a generic, so a name cannot come out
# as two settlements standing next to each other.
PLACE_QUALIFIERS = (
    "Bán",
    "Becc",
    "Cáel",
    "Crón",
    "Donn",
    "Dorcha",
    "Dub",
    "Fada",
    "Finn",
    "Fúar",
    "Garb",
    "Gel",
    "Glas",
    "Gorm",
    "Ísel",
    "Lethan",
    "Mín",
    "Mór",
    "Nua",
    "Riabach",
    "Ruad",
    "Sen",
    "Úr",
)

# What the land holds, already in the genitive: "Cill Dara" is the church of the oak. Stored inflected
# for the same reason the given names are - "dair" gives "dara" and "cú" gives "con", and no rule
# reaches both. None of them is the genitive of a generic, so no name says "the fort of the fort".
FEATURE_GENITIVES = (
    "Abann",
    "Bili",
    "Bó",
    "Cáerthainn",
    "Caírech",
    "Con",
    "Craíbe",
    "Cuilinn",
    "Daim",
    "Dara",
    "Draigin",
    "Eich",
    "Éisc",
    "Fedo",
    "Ferna",
    "Fiaich",
    "Gabra",
    "Gaíthe",
    "Ibair",
    "Luachra",
    "Mara",
    "Mela",
    "Muicce",
    "Muilinn",
    "Óenaig",
    "Sailech",
    "Sinnaig",
    "Trága",
    "Uisci",
)

# Bynames for telling two men of the same name apart. Colour and provenance only - "Áed Bán", "Cormac
# Muimnech" - so none of them makes a claim about the man's build, his speed, his health or his nerve,
# which is what his nickname is already for and could then contradict.
BYNAMES = (
    "Albanach",
    "Bán",
    "Bretnach",
    "Connachtach",
    "Crón",
    "Donn",
    "Dub",
    "Finn",
    "Gall",
    "Gel",
    "Glas",
    "Gorm",
    "Laignech",
    "Muimnech",
    "Riabach",
    "Ruad",
    "Ultach",
)
