# Generated by Django 4.1.5 on 2023-01-21 14:55

import django.db.models.deletion
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("faction", "0003_remove_faction_stored_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.PositiveSmallIntegerField(choices=[(1, "Weapon"), (2, "Armor")], verbose_name="Type")),
                ("price", models.PositiveSmallIntegerField(verbose_name="Price")),
                (
                    "value",
                    models.CharField(
                        max_length=10, validators=[apps.core.validators.dice_notation], verbose_name="Value"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faction.faction", verbose_name="Owning faction"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "default_related_name": "items",
            },
        ),
    ]
