# Generated by Django 4.1.5 on 2023-01-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "function",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Weapon"), (2, "Armor")], unique=True, verbose_name="Function"
                    ),
                ),
                ("svg_image_name", models.CharField(max_length=50, verbose_name="SVG image name")),
            ],
            options={
                "verbose_name": "Item type",
                "verbose_name_plural": "Item types",
                "default_related_name": "item_types",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="item.itemtype", verbose_name="Type"
            ),
        ),
    ]
