# Generated by Django 4.1.5 on 2023-01-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0005_alter_faction_culture"),
        ("item", "0002_itemtype_alter_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="faction.faction",
                verbose_name="Owning faction",
            ),
        ),
    ]
