# Generated by Django 4.1.5 on 2023-01-22 10:14

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_alter_item_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="base_value",
            field=models.CharField(
                default="2d3", max_length=10, validators=[apps.core.validators.dice_notation], verbose_name="Value"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemtype",
            name="name",
            field=models.CharField(default="Item", max_length=75, verbose_name="Name"),
            preserve_default=False,
        ),
    ]
