# Generated by Django 4.1.5 on 2023-01-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0004_itemtype_base_value_itemtype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtype",
            name="function",
            field=models.PositiveSmallIntegerField(choices=[(1, "Weapon"), (2, "Armor")], verbose_name="Function"),
        ),
    ]
