# Generated by Django 4.1.5 on 2023-01-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_alter_itemtype_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="is_fallback",
            field=models.BooleanField(default=0, verbose_name="Is fallback"),
        ),
    ]
