# Generated by Django 4.1.5 on 2023-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_itemtype_is_fallback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="value",
        ),
        migrations.AddField(
            model_name="item",
            name="modifier",
            field=models.PositiveSmallIntegerField(
                default=0, help_text='2d4+7 - this is the "7"', verbose_name="Modifier"
            ),
        ),
    ]
