# Generated by Django 4.1.5 on 2023-01-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0008_alter_item_modifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="condition",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Rusty"), (2, "Cheap"), (3, "Ordinary"), (4, "Superior")],
                default=3,
                verbose_name="Condition",
            ),
        ),
    ]
