# Generated by Django 4.1.5 on 2023-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0009_item_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="condition",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Rusty"), (2, "Cheap"), (3, "Traditional"), (4, "Superior")],
                default=3,
                verbose_name="Condition",
            ),
        ),
    ]
