# Generated by Django 6.1.1 on 2026-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0003_what_a_month_renews'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermonthlog',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Demands attention'), (2, 'Consequence'), (3, 'Upkeep'), (4, 'Chronicle')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='playermonthlog',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salaries unpaid'), (2, 'Warrior deserted'), (3, 'Salaries paid'), (4, 'Building income'), (5, 'Fyrd growth'), (6, 'Skill upgrade'), (7, 'Morale recovered'), (8, 'Wounds healed'), (9, 'Quests offered'), (10, 'Pub restocked'), (11, 'Shop restocked'), (12, 'Incident')], verbose_name='Kind'),
        ),
    ]
